//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.ServiceRefTCP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wsclientes.tcp.com.br", ConfigurationName="ServiceRefTCP.WebservicesClientes_ExportacaoCheioPortType")]
    public interface WebservicesClientes_ExportacaoCheioPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SolicitarOrdemEmbarqueDue", ReplyAction="urn:SolicitarOrdemEmbarqueDueTcpResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueResponse SolicitarOrdemEmbarqueDue(TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:SolicitarOrdemEmbarqueDue", ReplyAction="urn:SolicitarOrdemEmbarqueDueTcpResponse")]
        System.Threading.Tasks.Task<TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueResponse> SolicitarOrdemEmbarqueDueAsync(TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ConsultarMovimentacao", ReplyAction="urn:ConsultarMovimentacaoExpoCheioTcpResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoResponse ConsultarMovimentacao(TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ConsultarMovimentacao", ReplyAction="urn:ConsultarMovimentacaoExpoCheioTcpResponse")]
        System.Threading.Tasks.Task<TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoResponse> ConsultarMovimentacaoAsync(TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ConsultarDue", ReplyAction="urn:ConsultarDueTcpResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TerminalRobo.ServiceRefTCP.ConsultarDueResponse ConsultarDue(TerminalRobo.ServiceRefTCP.ConsultarDueRequest request);
        
        // CODEGEN: Gerando contrato de mensagem porque a operação tem vários valores de retorno.
        [System.ServiceModel.OperationContractAttribute(Action="urn:ConsultarDue", ReplyAction="urn:ConsultarDueTcpResponse")]
        System.Threading.Tasks.Task<TerminalRobo.ServiceRefTCP.ConsultarDueResponse> ConsultarDueAsync(TerminalRobo.ServiceRefTCP.ConsultarDueRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://wsclientes.tcp.com.br")]
    public partial class SolicitarOrdemEmbarqueDueTcpResponseOrdemEmbarqueDue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string protocoloField;
        
        private string numeroDUEField;
        
        private string numeroRUCField;
        
        private string exportadorField;
        
        private System.DateTime dataInclusaoField;
        
        private string[] conteineresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Protocolo {
            get {
                return this.protocoloField;
            }
            set {
                this.protocoloField = value;
                this.RaisePropertyChanged("Protocolo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NumeroDUE {
            get {
                return this.numeroDUEField;
            }
            set {
                this.numeroDUEField = value;
                this.RaisePropertyChanged("NumeroDUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NumeroRUC {
            get {
                return this.numeroRUCField;
            }
            set {
                this.numeroRUCField = value;
                this.RaisePropertyChanged("NumeroRUC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Exportador {
            get {
                return this.exportadorField;
            }
            set {
                this.exportadorField = value;
                this.RaisePropertyChanged("Exportador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime DataInclusao {
            get {
                return this.dataInclusaoField;
            }
            set {
                this.dataInclusaoField = value;
                this.RaisePropertyChanged("DataInclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Conteiner", IsNullable=false)]
        public string[] Conteineres {
            get {
                return this.conteineresField;
            }
            set {
                this.conteineresField = value;
                this.RaisePropertyChanged("Conteineres");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsclientes.tcp.com.br")]
    public partial class ConteinerType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string conteinerField;
        
        private string clienteField;
        
        private string lacreArmadorField;
        
        private string navioField;
        
        private System.Nullable<System.DateTime> deadlineField;
        
        private bool deadlineFieldSpecified;
        
        private string eventosField;
        
        private string avariasField;
        
        private string impeditivoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Conteiner {
            get {
                return this.conteinerField;
            }
            set {
                this.conteinerField = value;
                this.RaisePropertyChanged("Conteiner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("Cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string LacreArmador {
            get {
                return this.lacreArmadorField;
            }
            set {
                this.lacreArmadorField = value;
                this.RaisePropertyChanged("LacreArmador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Navio {
            get {
                return this.navioField;
            }
            set {
                this.navioField = value;
                this.RaisePropertyChanged("Navio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> Deadline {
            get {
                return this.deadlineField;
            }
            set {
                this.deadlineField = value;
                this.RaisePropertyChanged("Deadline");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeadlineSpecified {
            get {
                return this.deadlineFieldSpecified;
            }
            set {
                this.deadlineFieldSpecified = value;
                this.RaisePropertyChanged("DeadlineSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Eventos {
            get {
                return this.eventosField;
            }
            set {
                this.eventosField = value;
                this.RaisePropertyChanged("Eventos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Avarias {
            get {
                return this.avariasField;
            }
            set {
                this.avariasField = value;
                this.RaisePropertyChanged("Avarias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Impeditivo {
            get {
                return this.impeditivoField;
            }
            set {
                this.impeditivoField = value;
                this.RaisePropertyChanged("Impeditivo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wsclientes.tcp.com.br")]
    public partial class NotaFiscalType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroField;
        
        private string serieField;
        
        private string nCMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("Numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
                this.RaisePropertyChanged("Serie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string NCM {
            get {
                return this.nCMField;
            }
            set {
                this.nCMField = value;
                this.RaisePropertyChanged("NCM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://wsclientes.tcp.com.br")]
    public partial class RetornoValidacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private RetornoValidacaoIndicadorErro indicadorErroField;
        
        private RetornoValidacaoMensagemRetornoWs[] listaMensagemRetornoWsField;
        
        public RetornoValidacao() {
            this.indicadorErroField = RetornoValidacaoIndicadorErro.N;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RetornoValidacaoIndicadorErro IndicadorErro {
            get {
                return this.indicadorErroField;
            }
            set {
                this.indicadorErroField = value;
                this.RaisePropertyChanged("IndicadorErro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MensagemRetornoWs", IsNullable=false)]
        public RetornoValidacaoMensagemRetornoWs[] ListaMensagemRetornoWs {
            get {
                return this.listaMensagemRetornoWsField;
            }
            set {
                this.listaMensagemRetornoWsField = value;
                this.RaisePropertyChanged("ListaMensagemRetornoWs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://wsclientes.tcp.com.br")]
    public enum RetornoValidacaoIndicadorErro {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://wsclientes.tcp.com.br")]
    public partial class RetornoValidacaoMensagemRetornoWs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object codigoField;
        
        private object mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitarOrdemEmbarqueDueTcpRequest", WrapperNamespace="http://wsclientes.tcp.com.br", IsWrapped=true)]
    public partial class SolicitarOrdemEmbarqueDueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsclientes.tcp.com.br", Order=0)]
        public string NumeroDue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsclientes.tcp.com.br", Order=1)]
        public bool AceiteAvarias;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsclientes.tcp.com.br", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Conteiner", IsNullable=false)]
        public string[] Conteineres;
        
        public SolicitarOrdemEmbarqueDueRequest() {
        }
        
        public SolicitarOrdemEmbarqueDueRequest(string NumeroDue, bool AceiteAvarias, string[] Conteineres) {
            this.NumeroDue = NumeroDue;
            this.AceiteAvarias = AceiteAvarias;
            this.Conteineres = Conteineres;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SolicitarOrdemEmbarqueDueTcpResponse", WrapperNamespace="http://wsclientes.tcp.com.br", IsWrapped=true)]
    public partial class SolicitarOrdemEmbarqueDueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsclientes.tcp.com.br", Order=0)]
        public TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueTcpResponseOrdemEmbarqueDue OrdemEmbarqueDue;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsclientes.tcp.com.br", Order=1)]
        public TerminalRobo.ServiceRefTCP.RetornoValidacao RetornoValidacao;
        
        public SolicitarOrdemEmbarqueDueResponse() {
        }
        
        public SolicitarOrdemEmbarqueDueResponse(TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueTcpResponseOrdemEmbarqueDue OrdemEmbarqueDue, TerminalRobo.ServiceRefTCP.RetornoValidacao RetornoValidacao) {
            this.OrdemEmbarqueDue = OrdemEmbarqueDue;
            this.RetornoValidacao = RetornoValidacao;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://wsclientes.tcp.com.br")]
    public partial class RequestHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string empresaSelecionadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EmpresaSelecionada {
            get {
                return this.empresaSelecionadaField;
            }
            set {
                this.empresaSelecionadaField = value;
                this.RaisePropertyChanged("EmpresaSelecionada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://wsclientes.tcp.com.br")]
    public partial class ConsultarMovimentacaoExpoCheioTcpResponseMovimentacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string navioField;
        
        private string navioViagemField;
        
        private string viagemField;
        
        private System.Nullable<System.DateTime> atracacaoNavioField;
        
        private bool atracacaoNavioFieldSpecified;
        
        private string clienteField;
        
        private string destinatarioField;
        
        private string destinoField;
        
        private string armadorField;
        
        private string bookingField;
        
        private System.Nullable<System.DateTime> deadlineCargaField;
        
        private bool deadlineCargaFieldSpecified;
        
        private string conteinerField;
        
        private string isoField;
        
        private System.Nullable<System.DateTime> dataChegadaField;
        
        private bool dataChegadaFieldSpecified;
        
        private System.Nullable<System.DateTime> recepcaoCctField;
        
        private bool recepcaoCctFieldSpecified;
        
        private string ordemDeEmbarqueField;
        
        private System.Nullable<System.DateTime> dataEmbarqueField;
        
        private bool dataEmbarqueFieldSpecified;
        
        private System.Nullable<System.DateTime> entregaCctField;
        
        private bool entregaCctFieldSpecified;
        
        private string ddeDueField;
        
        private string taraField;
        
        private string lacreArmadorField;
        
        private string lacreSifField;
        
        private string numeroSifField;
        
        private NotaFiscalType[] notasFiscaisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Navio {
            get {
                return this.navioField;
            }
            set {
                this.navioField = value;
                this.RaisePropertyChanged("Navio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string NavioViagem {
            get {
                return this.navioViagemField;
            }
            set {
                this.navioViagemField = value;
                this.RaisePropertyChanged("NavioViagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Viagem {
            get {
                return this.viagemField;
            }
            set {
                this.viagemField = value;
                this.RaisePropertyChanged("Viagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> AtracacaoNavio {
            get {
                return this.atracacaoNavioField;
            }
            set {
                this.atracacaoNavioField = value;
                this.RaisePropertyChanged("AtracacaoNavio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AtracacaoNavioSpecified {
            get {
                return this.atracacaoNavioFieldSpecified;
            }
            set {
                this.atracacaoNavioFieldSpecified = value;
                this.RaisePropertyChanged("AtracacaoNavioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("Cliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Destinatario {
            get {
                return this.destinatarioField;
            }
            set {
                this.destinatarioField = value;
                this.RaisePropertyChanged("Destinatario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Destino {
            get {
                return this.destinoField;
            }
            set {
                this.destinoField = value;
                this.RaisePropertyChanged("Destino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Armador {
            get {
                return this.armadorField;
            }
            set {
                this.armadorField = value;
                this.RaisePropertyChanged("Armador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string Booking {
            get {
                return this.bookingField;
            }
            set {
                this.bookingField = value;
                this.RaisePropertyChanged("Booking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> DeadlineCarga {
            get {
                return this.deadlineCargaField;
            }
            set {
                this.deadlineCargaField = value;
                this.RaisePropertyChanged("DeadlineCarga");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeadlineCargaSpecified {
            get {
                return this.deadlineCargaFieldSpecified;
            }
            set {
                this.deadlineCargaFieldSpecified = value;
                this.RaisePropertyChanged("DeadlineCargaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string Conteiner {
            get {
                return this.conteinerField;
            }
            set {
                this.conteinerField = value;
                this.RaisePropertyChanged("Conteiner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string Iso {
            get {
                return this.isoField;
            }
            set {
                this.isoField = value;
                this.RaisePropertyChanged("Iso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> DataChegada {
            get {
                return this.dataChegadaField;
            }
            set {
                this.dataChegadaField = value;
                this.RaisePropertyChanged("DataChegada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataChegadaSpecified {
            get {
                return this.dataChegadaFieldSpecified;
            }
            set {
                this.dataChegadaFieldSpecified = value;
                this.RaisePropertyChanged("DataChegadaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<System.DateTime> RecepcaoCct {
            get {
                return this.recepcaoCctField;
            }
            set {
                this.recepcaoCctField = value;
                this.RaisePropertyChanged("RecepcaoCct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecepcaoCctSpecified {
            get {
                return this.recepcaoCctFieldSpecified;
            }
            set {
                this.recepcaoCctFieldSpecified = value;
                this.RaisePropertyChanged("RecepcaoCctSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string OrdemDeEmbarque {
            get {
                return this.ordemDeEmbarqueField;
            }
            set {
                this.ordemDeEmbarqueField = value;
                this.RaisePropertyChanged("OrdemDeEmbarque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<System.DateTime> DataEmbarque {
            get {
                return this.dataEmbarqueField;
            }
            set {
                this.dataEmbarqueField = value;
                this.RaisePropertyChanged("DataEmbarque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataEmbarqueSpecified {
            get {
                return this.dataEmbarqueFieldSpecified;
            }
            set {
                this.dataEmbarqueFieldSpecified = value;
                this.RaisePropertyChanged("DataEmbarqueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public System.Nullable<System.DateTime> EntregaCct {
            get {
                return this.entregaCctField;
            }
            set {
                this.entregaCctField = value;
                this.RaisePropertyChanged("EntregaCct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntregaCctSpecified {
            get {
                return this.entregaCctFieldSpecified;
            }
            set {
                this.entregaCctFieldSpecified = value;
                this.RaisePropertyChanged("EntregaCctSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string DdeDue {
            get {
                return this.ddeDueField;
            }
            set {
                this.ddeDueField = value;
                this.RaisePropertyChanged("DdeDue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string Tara {
            get {
                return this.taraField;
            }
            set {
                this.taraField = value;
                this.RaisePropertyChanged("Tara");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string LacreArmador {
            get {
                return this.lacreArmadorField;
            }
            set {
                this.lacreArmadorField = value;
                this.RaisePropertyChanged("LacreArmador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string LacreSif {
            get {
                return this.lacreSifField;
            }
            set {
                this.lacreSifField = value;
                this.RaisePropertyChanged("LacreSif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string NumeroSif {
            get {
                return this.numeroSifField;
            }
            set {
                this.numeroSifField = value;
                this.RaisePropertyChanged("NumeroSif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=22)]
        [System.Xml.Serialization.XmlArrayItemAttribute("NotaFiscal", IsNullable=false)]
        public NotaFiscalType[] NotasFiscais {
            get {
                return this.notasFiscaisField;
            }
            set {
                this.notasFiscaisField = value;
                this.RaisePropertyChanged("NotasFiscais");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarMovimentacaoExpoCheioTcpRequest", WrapperNamespace="http://wsclientes.tcp.com.br", IsWrapped=true)]
    public partial class ConsultarMovimentacaoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://wsclientes.tcp.com.br")]
        public TerminalRobo.ServiceRefTCP.RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsclientes.tcp.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsclientes.tcp.com.br", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DataFim;
        
        public ConsultarMovimentacaoRequest() {
        }
        
        public ConsultarMovimentacaoRequest(TerminalRobo.ServiceRefTCP.RequestHeader RequestHeader, System.DateTime DataInicio, System.DateTime DataFim) {
            this.RequestHeader = RequestHeader;
            this.DataInicio = DataInicio;
            this.DataFim = DataFim;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarMovimentacaoExpoCheioTcpResponse", WrapperNamespace="http://wsclientes.tcp.com.br", IsWrapped=true)]
    public partial class ConsultarMovimentacaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsclientes.tcp.com.br", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Movimentacao")]
        public TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoExpoCheioTcpResponseMovimentacao[] Movimentacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsclientes.tcp.com.br", Order=1)]
        public TerminalRobo.ServiceRefTCP.RetornoValidacao RetornoValidacao;
        
        public ConsultarMovimentacaoResponse() {
        }
        
        public ConsultarMovimentacaoResponse(TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoExpoCheioTcpResponseMovimentacao[] Movimentacao, TerminalRobo.ServiceRefTCP.RetornoValidacao RetornoValidacao) {
            this.Movimentacao = Movimentacao;
            this.RetornoValidacao = RetornoValidacao;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://wsclientes.tcp.com.br")]
    public partial class ConsultarDueTcpResponseDue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroDUEField;
        
        private string numeroRUCField;
        
        private string exportadorField;
        
        private string situacaoField;
        
        private ConteinerType[] conteineresField;
        
        private ConsultarDueTcpResponseDueTermoAvarias termoAvariasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NumeroDUE {
            get {
                return this.numeroDUEField;
            }
            set {
                this.numeroDUEField = value;
                this.RaisePropertyChanged("NumeroDUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NumeroRUC {
            get {
                return this.numeroRUCField;
            }
            set {
                this.numeroRUCField = value;
                this.RaisePropertyChanged("NumeroRUC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Exportador {
            get {
                return this.exportadorField;
            }
            set {
                this.exportadorField = value;
                this.RaisePropertyChanged("Exportador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Situacao {
            get {
                return this.situacaoField;
            }
            set {
                this.situacaoField = value;
                this.RaisePropertyChanged("Situacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Conteiner", IsNullable=false)]
        public ConteinerType[] Conteineres {
            get {
                return this.conteineresField;
            }
            set {
                this.conteineresField = value;
                this.RaisePropertyChanged("Conteineres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ConsultarDueTcpResponseDueTermoAvarias TermoAvarias {
            get {
                return this.termoAvariasField;
            }
            set {
                this.termoAvariasField = value;
                this.RaisePropertyChanged("TermoAvarias");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://wsclientes.tcp.com.br")]
    public partial class ConsultarDueTcpResponseDueTermoAvarias : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string conteudoField;
        
        private string[] conteinerAvariaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Conteudo {
            get {
                return this.conteudoField;
            }
            set {
                this.conteudoField = value;
                this.RaisePropertyChanged("Conteudo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConteinerAvaria", IsNullable=true, Order=1)]
        public string[] ConteinerAvaria {
            get {
                return this.conteinerAvariaField;
            }
            set {
                this.conteinerAvariaField = value;
                this.RaisePropertyChanged("ConteinerAvaria");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarDueTcpRequest", WrapperNamespace="http://wsclientes.tcp.com.br", IsWrapped=true)]
    public partial class ConsultarDueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsclientes.tcp.com.br", Order=0)]
        public string NumeroDue;
        
        public ConsultarDueRequest() {
        }
        
        public ConsultarDueRequest(string NumeroDue) {
            this.NumeroDue = NumeroDue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConsultarDueTcpResponse", WrapperNamespace="http://wsclientes.tcp.com.br", IsWrapped=true)]
    public partial class ConsultarDueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsclientes.tcp.com.br", Order=0)]
        public TerminalRobo.ServiceRefTCP.ConsultarDueTcpResponseDue Due;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://wsclientes.tcp.com.br", Order=1)]
        public TerminalRobo.ServiceRefTCP.RetornoValidacao RetornoValidacao;
        
        public ConsultarDueResponse() {
        }
        
        public ConsultarDueResponse(TerminalRobo.ServiceRefTCP.ConsultarDueTcpResponseDue Due, TerminalRobo.ServiceRefTCP.RetornoValidacao RetornoValidacao) {
            this.Due = Due;
            this.RetornoValidacao = RetornoValidacao;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebservicesClientes_ExportacaoCheioPortTypeChannel : TerminalRobo.ServiceRefTCP.WebservicesClientes_ExportacaoCheioPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebservicesClientes_ExportacaoCheioPortTypeClient : System.ServiceModel.ClientBase<TerminalRobo.ServiceRefTCP.WebservicesClientes_ExportacaoCheioPortType>, TerminalRobo.ServiceRefTCP.WebservicesClientes_ExportacaoCheioPortType {
        
        public WebservicesClientes_ExportacaoCheioPortTypeClient() {
        }
        
        public WebservicesClientes_ExportacaoCheioPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebservicesClientes_ExportacaoCheioPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebservicesClientes_ExportacaoCheioPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebservicesClientes_ExportacaoCheioPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueResponse TerminalRobo.ServiceRefTCP.WebservicesClientes_ExportacaoCheioPortType.SolicitarOrdemEmbarqueDue(TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueRequest request) {
            return base.Channel.SolicitarOrdemEmbarqueDue(request);
        }
        
        public TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueTcpResponseOrdemEmbarqueDue SolicitarOrdemEmbarqueDue(string NumeroDue, bool AceiteAvarias, string[] Conteineres, out TerminalRobo.ServiceRefTCP.RetornoValidacao RetornoValidacao) {
            TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueRequest inValue = new TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueRequest();
            inValue.NumeroDue = NumeroDue;
            inValue.AceiteAvarias = AceiteAvarias;
            inValue.Conteineres = Conteineres;
            TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueResponse retVal = ((TerminalRobo.ServiceRefTCP.WebservicesClientes_ExportacaoCheioPortType)(this)).SolicitarOrdemEmbarqueDue(inValue);
            RetornoValidacao = retVal.RetornoValidacao;
            return retVal.OrdemEmbarqueDue;
        }
        
        public System.Threading.Tasks.Task<TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueResponse> SolicitarOrdemEmbarqueDueAsync(TerminalRobo.ServiceRefTCP.SolicitarOrdemEmbarqueDueRequest request) {
            return base.Channel.SolicitarOrdemEmbarqueDueAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoResponse TerminalRobo.ServiceRefTCP.WebservicesClientes_ExportacaoCheioPortType.ConsultarMovimentacao(TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoRequest request) {
            return base.Channel.ConsultarMovimentacao(request);
        }
        
        public TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoExpoCheioTcpResponseMovimentacao[] ConsultarMovimentacao(TerminalRobo.ServiceRefTCP.RequestHeader RequestHeader, System.DateTime DataInicio, System.DateTime DataFim, out TerminalRobo.ServiceRefTCP.RetornoValidacao RetornoValidacao) {
            TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoRequest inValue = new TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoRequest();
            inValue.RequestHeader = RequestHeader;
            inValue.DataInicio = DataInicio;
            inValue.DataFim = DataFim;
            TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoResponse retVal = ((TerminalRobo.ServiceRefTCP.WebservicesClientes_ExportacaoCheioPortType)(this)).ConsultarMovimentacao(inValue);
            RetornoValidacao = retVal.RetornoValidacao;
            return retVal.Movimentacao;
        }
        
        public System.Threading.Tasks.Task<TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoResponse> ConsultarMovimentacaoAsync(TerminalRobo.ServiceRefTCP.ConsultarMovimentacaoRequest request) {
            return base.Channel.ConsultarMovimentacaoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TerminalRobo.ServiceRefTCP.ConsultarDueResponse TerminalRobo.ServiceRefTCP.WebservicesClientes_ExportacaoCheioPortType.ConsultarDue(TerminalRobo.ServiceRefTCP.ConsultarDueRequest request) {
            return base.Channel.ConsultarDue(request);
        }
        
        public TerminalRobo.ServiceRefTCP.ConsultarDueTcpResponseDue ConsultarDue(string NumeroDue, out TerminalRobo.ServiceRefTCP.RetornoValidacao RetornoValidacao) {
            TerminalRobo.ServiceRefTCP.ConsultarDueRequest inValue = new TerminalRobo.ServiceRefTCP.ConsultarDueRequest();
            inValue.NumeroDue = NumeroDue;
            TerminalRobo.ServiceRefTCP.ConsultarDueResponse retVal = ((TerminalRobo.ServiceRefTCP.WebservicesClientes_ExportacaoCheioPortType)(this)).ConsultarDue(inValue);
            RetornoValidacao = retVal.RetornoValidacao;
            return retVal.Due;
        }
        
        public System.Threading.Tasks.Task<TerminalRobo.ServiceRefTCP.ConsultarDueResponse> ConsultarDueAsync(TerminalRobo.ServiceRefTCP.ConsultarDueRequest request) {
            return base.Channel.ConsultarDueAsync(request);
        }
    }
}
