//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVISOS_PRE_PROCESSO
    {
        public int CD_AVISO { get; set; }
        public Nullable<int> CD_PRE_PROCESSO { get; set; }
        public string DS_MENSAGEM { get; set; }
        public Nullable<System.DateTime> DT_AVISO { get; set; }
        public Nullable<bool> IC_LIDO { get; set; }
        public Nullable<System.DateTime> DT_LEITURA { get; set; }
        public Nullable<int> CD_USUARIO_LEU { get; set; }
    }
}
