//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class BTP_IMPORTAR_EXCEL
    {
        public int CD_IMPORTAR_EXCEL_BTP { get; set; }
        public string NM_ARQUIVO_EXCEL { get; set; }
        public Nullable<int> CD_USUARIO { get; set; }
        public Nullable<System.DateTime> DT_CADASTRO { get; set; }
        public Nullable<System.DateTime> DT_PROCESSAMENTO { get; set; }
        public Nullable<int> CD_GRUPO { get; set; }
        public Nullable<bool> IC_PROCESSADO { get; set; }
    }
}
