//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTAINER
    {
        public CONTAINER()
        {
            this.PROCESSORESERVACONTAINER = new HashSet<PROCESSORESERVACONTAINER>();
        }
    
        public int CD_CONTAINER { get; set; }
        public string CD_NUMERO_CONTAINER { get; set; }
        public int CD_TIPO_CONTAINER { get; set; }
        public string DS_TAMANHO { get; set; }
        public Nullable<decimal> QT_TARA { get; set; }
        public Nullable<decimal> QT_PESO_BRUTO { get; set; }
        public string DS_LACRE_AGENCIA { get; set; }
        public string DS_LACRE_SIF { get; set; }
        public string DS_LACRE_3 { get; set; }
        public string DS_LACRE_4 { get; set; }
        public Nullable<decimal> QT_PESO_LIQUIDO { get; set; }
        public Nullable<int> QT_VOLUME { get; set; }
        public string DS_TEMPERATURA { get; set; }
        public Nullable<decimal> VL_FRETE { get; set; }
        public string SG_TIPO_TEMPERATURA { get; set; }
        public Nullable<int> QT_TEMPERATURA { get; set; }
        public Nullable<System.DateTime> DT_ENTRADA { get; set; }
        public Nullable<System.DateTime> DT_AGENDAMENTO { get; set; }
        public Nullable<System.DateTime> DT_ESTUFAGEM { get; set; }
        public Nullable<System.DateTime> DT_SAIDA { get; set; }
        public Nullable<bool> IC_MULTI_GOODS { get; set; }
        public string STR_CODIGOESPECIE { get; set; }
        public string DS_DESCMERCADORIA { get; set; }
        public Nullable<double> VL_CUBAGEM { get; set; }
        public Nullable<int> CD_TERMINAL_REDEX { get; set; }
        public Nullable<System.DateTime> DT_REDEX { get; set; }
        public Nullable<System.DateTime> DT_DEPOSITO_TERM_EMBARQUE { get; set; }
        public string DS_LACRE_AGENCIA_BL { get; set; }
        public string DS_LACRE_SIF_BL { get; set; }
        public string DS_LACRE_3_BL { get; set; }
        public string DS_LACRE_4_BL { get; set; }
        public Nullable<int> CD_PROCESSORESERVACONTAINER_ULTIMO { get; set; }
        public Nullable<int> CD_PROCESSORESERVACONTAINER_DUE_NF_ULTIMO { get; set; }
        public Nullable<int> CD_DUE_NF_LPCO { get; set; }
        public Nullable<int> CD_TERMINAL_REDEX_PRC { get; set; }
        public Nullable<System.DateTime> DT_REDEX_PRC { get; set; }
        public Nullable<System.DateTime> DT_DEPOSITO_TERM_EMBARQUE_PRC { get; set; }
        public Nullable<System.DateTime> DT_CHEGADA_NF { get; set; }
        public Nullable<System.DateTime> DT_CHEGADA_CSI { get; set; }
        public Nullable<System.DateTime> DT_PRESENCA_CARGA { get; set; }
        public Nullable<System.DateTime> DT_ENTRADA_TF { get; set; }
        public Nullable<System.DateTime> DT_EMBARQUE { get; set; }
        public Nullable<int> CD_TRANSPORTADORA { get; set; }
        public string NR_CSI { get; set; }
        public Nullable<System.DateTime> DT_DESPACHO_PROTOCOLADO { get; set; }
        public Nullable<int> NR_ORDEM_CONTAINER { get; set; }
        public string IC_CONFERENCIA_FISICA { get; set; }
        public Nullable<System.DateTime> DT_CONFERENCIA_FISICA { get; set; }
        public Nullable<int> CD_ARMAZEM { get; set; }
        public string NR_LPCO { get; set; }
        public string IC_SITUACAO_LPCO { get; set; }
        public Nullable<System.DateTime> DT_REGISTRO_LPCO { get; set; }
        public Nullable<System.DateTime> DT_SITUACAO_DEFERIDO { get; set; }
        public Nullable<System.DateTime> DT_EXIGENCIA { get; set; }
        public Nullable<System.DateTime> DT_CANCELADO { get; set; }
        public Nullable<System.DateTime> DT_ESGOTADO { get; set; }
        public Nullable<System.DateTime> DT_RESPOSTA_EXIGENCIA { get; set; }
        public Nullable<System.DateTime> DT_ANULADO_REVOGADO { get; set; }
        public Nullable<System.DateTime> DT_EM_VERIFICACAO { get; set; }
        public Nullable<System.DateTime> DT_EM_INSPECAO { get; set; }
        public Nullable<System.DateTime> DT_VENCIDO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_SITUACAO_INDEFERIDO { get; set; }
        public Nullable<System.DateTime> DT_EM_EXIGENCIA { get; set; }
        public string NR_ORDDEM_CLIENTE { get; set; }
        public Nullable<bool> IC_BREAK_BULK { get; set; }
        public string TEMPERATURE_RECORDER { get; set; }
    
        public virtual ICollection<PROCESSORESERVACONTAINER> PROCESSORESERVACONTAINER { get; set; }
    }
}
