//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDE
    {
        public int CD_DDE { get; set; }
        public string CD_NUMERO_DDE { get; set; }
        public string CD_NUMERO_DESPACHO { get; set; }
        public Nullable<System.DateTime> DT_DESPACHO { get; set; }
        public Nullable<int> CD_UNIDADE_OPERACIONAL { get; set; }
        public Nullable<int> CD_EXPORTADOR { get; set; }
        public Nullable<int> QT_ESTABELECIMENTOS_DESPACHO { get; set; }
        public string STR_CODIGOVIATRANSPORTE { get; set; }
        public Nullable<decimal> QT_TOTAL_PESO_LIQUIDO { get; set; }
        public Nullable<decimal> QT_TOTAL_PESO_BRUTO { get; set; }
        public string DS_RECINTO { get; set; }
        public Nullable<decimal> VL_TOTAL_CONDICAO_VENDA { get; set; }
        public string DS_SETOR { get; set; }
        public string NM_USUARIO_RESPONSAVEL { get; set; }
        public string CD_EMBARCACAO { get; set; }
        public string DS_NACIONALIDADE_EMBARCACAO { get; set; }
        public Nullable<System.DateTime> DT_VALIDADE_EMBARQUE { get; set; }
        public Nullable<bool> IC_MERCADORIA_CCPTC { get; set; }
        public string DS_REGIMES_ADUANEIROS { get; set; }
        public Nullable<bool> IC_INF_REPRESENTANTE { get; set; }
        public Nullable<bool> IC_INF_DESPACHO { get; set; }
        public Nullable<bool> IC_INF_CARGA_FRACIONADA { get; set; }
        public Nullable<bool> IC_OUTROS_DOCUMENTOS { get; set; }
        public Nullable<bool> IC_PRESENCAO_CARGA { get; set; }
        public Nullable<bool> IC_DADOS_EMBARQUE { get; set; }
        public string STR_CODIGOUNIDADERF_DESPACHO { get; set; }
        public string STR_CODIGOUNIDADERF_EMBARQUE { get; set; }
        public string CD_NUMERO_NAO_ALFANDEGADO { get; set; }
        public string STR_CODIGOUNIDADERF_RECINTO { get; set; }
        public string DS_VEICULO_TRANSPORTADOR { get; set; }
        public Nullable<int> QT_TOTAL_VOLUMES { get; set; }
        public Nullable<int> QT_VOLUMES_ACUMULADOS { get; set; }
        public string DS_FINALIDADE { get; set; }
        public string CD_ESTABELECIMENTO { get; set; }
        public string CD_SUFIXO_CNPJMF { get; set; }
        public Nullable<int> CD_PROCESSO { get; set; }
        public Nullable<bool> IC_RE_MANUAL { get; set; }
        public Nullable<int> CD_USUARIO_DDE { get; set; }
        public Nullable<int> CD_USUARIO_DDE_TRANSMITIDO { get; set; }
        public Nullable<bool> IC_CONFIRMADO { get; set; }
        public Nullable<int> ID_SITUACAO_ATUAL { get; set; }
        public string DS_OBSERVACAO { get; set; }
        public Nullable<decimal> VL_ALIQUOTA { get; set; }
        public string DS_BASE_LEGAL { get; set; }
        public Nullable<bool> IC_TRANSMISSAO_WEB { get; set; }
        public Nullable<bool> IC_CANCELADA { get; set; }
        public Nullable<System.DateTime> DT_DESEMBARACO { get; set; }
        public Nullable<System.DateTime> DT_ENTREGA_DESPACHO { get; set; }
        public Nullable<System.DateTime> DT_CANAL_VERMELHO { get; set; }
        public Nullable<bool> IC_EXTRATO_SD { get; set; }
        public Nullable<System.DateTime> DT_ULTIMA_CONSULTA { get; set; }
        public Nullable<System.DateTime> DT_ENVIADO_DESEMBARACO_SISCOMEX { get; set; }
        public Nullable<System.DateTime> DT_LIBERADO_DESEMBARACO { get; set; }
        public Nullable<int> CD_USUARIO_LIBEROU_DESEMBARACO { get; set; }
        public Nullable<bool> IC_LIBERA_CONSULTA { get; set; }
    
        public virtual PROCESSOS PROCESSOS { get; set; }
        public virtual UNIDRF UNIDRF { get; set; }
        public virtual UNIDRF UNIDRF1 { get; set; }
        public virtual RECIALFA RECIALFA { get; set; }
        public virtual ENTIDADE ENTIDADE { get; set; }
        public virtual ENTIDADE ENTIDADE1 { get; set; }
    }
}
