//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUE
    {
        public DUE()
        {
            this.DUE_NF = new HashSet<DUE_NF>();
            this.DUE_NF_ITEM = new HashSet<DUE_NF_ITEM>();
            this.PROCESSO_LOTE = new HashSet<PROCESSO_LOTE>();
        }
    
        public int CD_DUE { get; set; }
        public Nullable<int> CD_PROCESSO { get; set; }
        public Nullable<System.DateTime> DT_DUE { get; set; }
        public string CD_NUMERO_DUE { get; set; }
        public string CD_NUMERO_RUC { get; set; }
        public string STR_CODIGOMOEDA { get; set; }
        public string DS_SITUACAO { get; set; }
        public Nullable<int> CD_EXPORTADOR { get; set; }
        public string CD_FORMA_EXPORTACAO { get; set; }
        public string STR_CODIGOUNIDADERF_DESPACHO { get; set; }
        public string CD_RECINTO_DESPACHO { get; set; }
        public Nullable<int> IC_RECINTO_ADUANEIRO_DESPACHO { get; set; }
        public string STR_CODIGOUNIDADERF_EMBARQUE { get; set; }
        public string CD_RECINTO_EMBARQUE { get; set; }
        public Nullable<int> IC_RECINTO_ADUANEIRO_EMBARQUE { get; set; }
        public string DS_REFERENCIA_ENDERECO { get; set; }
        public string DS_INFORMACOES_COMPLEMENTARES { get; set; }
        public Nullable<int> CD_VIA_TRANSPORTE_ESPECIAL { get; set; }
        public Nullable<decimal> VL_FRETE_INTERNACIONAL { get; set; }
        public Nullable<int> CD_USUARIO_DUE { get; set; }
        public Nullable<decimal> VL_DESCONTO { get; set; }
        public Nullable<int> IC_STATUS_PARA_ENVIO_TRANSMISSAO { get; set; }
        public Nullable<bool> SG_FRETE_INTERNACIONAL_EMBUTIDO { get; set; }
        public Nullable<bool> SG_SEGURO_INTERNACIONAL_EMBUTIDO { get; set; }
        public Nullable<decimal> VL_SEGURO { get; set; }
        public Nullable<System.DateTime> DT_TRANSMISSAO { get; set; }
        public Nullable<int> CD_USUARIO_TRANSMISSAO { get; set; }
        public Nullable<System.DateTime> DT_DESEMBARACO { get; set; }
        public Nullable<int> SG_TIPO_DUE { get; set; }
        public string DS_REFERENCIA { get; set; }
        public Nullable<int> CD_USUARIO_RETIRICAR { get; set; }
        public string DS_ARQUIVO_XML { get; set; }
        public Nullable<System.DateTime> DT_CANCELADO { get; set; }
        public Nullable<int> CD_USUARIO_CANCELOU { get; set; }
        public Nullable<System.DateTime> DT_CANAL_VERMELHO { get; set; }
        public Nullable<System.DateTime> DT_ENTREGA_DESPACHO { get; set; }
        public Nullable<System.DateTime> DT_BLOQUEIO_ADM { get; set; }
        public Nullable<int> IC_BLOQUEIO { get; set; }
        public Nullable<int> IC_CONTROLE_ADM { get; set; }
        public Nullable<int> IC_SITUACAO_CARGA { get; set; }
        public Nullable<System.DateTime> DT_DEPOSITADO { get; set; }
        public Nullable<System.DateTime> DT_DIVERGENCIA_RECINTO { get; set; }
        public Nullable<System.DateTime> DT_ANALISE_FISCAL { get; set; }
        public Nullable<System.DateTime> DT_EXPIRACAO_PRAZO { get; set; }
        public Nullable<int> CD_USUARIO_ENVIO_TERMINAL_EMBARQUE { get; set; }
        public string CD_CHAVE_ACESSO { get; set; }
        public Nullable<System.DateTime> DT_ABERBADO { get; set; }
        public Nullable<int> SG_TIPO_DUE_ANT { get; set; }
        public string CD_MOTIVO_DISPENSA_NF { get; set; }
        public string NR_CNPJ { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_REGISTRO { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_AVERBADO { get; set; }
        public string NR_CHAVE_NF { get; set; }
        public Nullable<int> CD_STATUS_HISTORICO { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_MENSAL_REGISTRO { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_EXTRATO_REGISTRADA { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_EXTRATO_AVERBADA { get; set; }
        public Nullable<int> IC_GERADO_EXTRATO_DUE_REGISTRADA { get; set; }
        public Nullable<int> IC_GERADO_EXTRATO_DUE_AVERBADA { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_EXTRATO_DIARIA_AVERBADA { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_EXTRATO_AVERBADA_SPED { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_EXTRATO_REGISTRADA_FTP { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_EXTRATO_AVERBADA_FTP { get; set; }
        public Nullable<bool> IC_LOCAL_EMBARQUE_TRANSPOSICAO_FRONTEIRA { get; set; }
    
        public virtual ENTIDADE ENTIDADE { get; set; }
        public virtual ICollection<DUE_NF> DUE_NF { get; set; }
        public virtual ICollection<DUE_NF_ITEM> DUE_NF_ITEM { get; set; }
        public virtual PROCESSOS PROCESSOS { get; set; }
        public virtual RECIALFA RECIALFA { get; set; }
        public virtual RECIALFA RECIALFA1 { get; set; }
        public virtual UNIDRF UNIDRF { get; set; }
        public virtual UNIDRF UNIDRF1 { get; set; }
        public virtual ICollection<PROCESSO_LOTE> PROCESSO_LOTE { get; set; }
    }
}
