//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUE_NF
    {
        public DUE_NF()
        {
            this.DUE_NF_ITEM = new HashSet<DUE_NF_ITEM>();
        }
    
        public int CD_NF { get; set; }
        public Nullable<int> CD_DUE { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO { get; set; }
        public Nullable<System.DateTime> DT_SAIDA { get; set; }
        public Nullable<int> CD_CLIENTE { get; set; }
        public string CD_NUMERO_CHAVE_NF { get; set; }
        public string CD_NUMERO_NF { get; set; }
        public string CD_SERIE_NF { get; set; }
        public string CD_NATUREZA_OPERACAO { get; set; }
        public string CD_CNPJ { get; set; }
        public string DS_ENDERECO_DESTINATARIO { get; set; }
        public string DS_BAIRRO_DESTINATARIO { get; set; }
        public string DS_CEP_DESTINATARIO { get; set; }
        public string DS_MUNICIPIO_DESTINATARIO { get; set; }
        public string DS_UF_DESTINATARIO { get; set; }
        public string DS_FONE_DESTINATARIO { get; set; }
        public string DS_FATURA { get; set; }
        public Nullable<decimal> VL_TOTAL_PRODUTO { get; set; }
        public Nullable<decimal> VL_TOTAL_NOTA { get; set; }
        public string DS_TRANSPORTADOR { get; set; }
        public string DS_PLACA_VEICULO { get; set; }
        public string DS_ESTADO_VEICULO { get; set; }
        public string CD_CNPJ_TRANSPORTADOR { get; set; }
        public string DS_ENDERECO_TRANSPORTADOR { get; set; }
        public string DS_MUNICIPIO_TRANSPORTADOR { get; set; }
        public string DS_ESTADO_TRANSPORTADOR { get; set; }
        public string CD_INSC_ESTADUAL_TRANSPORTADOR { get; set; }
        public Nullable<decimal> QTD_TOTAL { get; set; }
        public string DS_ESPECIE { get; set; }
        public Nullable<decimal> VL_PESO_BRUTO { get; set; }
        public Nullable<decimal> VL_PESO_LIQUIDO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public string DS_NOME_DESTINATARIO { get; set; }
        public Nullable<System.DateTime> DT_CANCELADA { get; set; }
        public Nullable<int> CD_USUARIO_CANCELOU { get; set; }
        public Nullable<decimal> VL_TOTAL_CONDICAO_VENDA_DOLAR { get; set; }
        public string NR_CFOP { get; set; }
        public string DS_OBSERVACAO { get; set; }
        public Nullable<bool> SG_NF { get; set; }
        public Nullable<decimal> VL_TOTAL_FINANCIADO { get; set; }
        public string NR_LPCO { get; set; }
        public Nullable<int> CD_PROCESSORESERVACONTAINER { get; set; }
        public Nullable<int> CD_USO_PROPOSTO { get; set; }
        public Nullable<int> CD_SITUACAO_ESPECIAL { get; set; }
        public string CD_UNIDADE_VIGIAGRO { get; set; }
        public Nullable<int> CD_DUE_NF_LPCO { get; set; }
        public Nullable<int> QTD_NOTA_REFERENCIADA { get; set; }
    
        public virtual DUE DUE { get; set; }
        public virtual ICollection<DUE_NF_ITEM> DUE_NF_ITEM { get; set; }
    }
}
