//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUE_NF_ITEM
    {
        public int CD_NF_ITEM { get; set; }
        public int CD_DUE { get; set; }
        public Nullable<int> CD_NF { get; set; }
        public int CD_ITEM { get; set; }
        public string STR_CODIGONCM { get; set; }
        public string STR_CODIGONALADI { get; set; }
        public string DS_MERCADORIA { get; set; }
        public string DS_DESCRICAO_COMPLEMENTAR { get; set; }
        public string STR_CODIGONCM_DESTAQUE { get; set; }
        public string CD_PAIS_DESTINO { get; set; }
        public string CD_TRATAMENTO_PRIORITARIO { get; set; }
        public string STR_CODIGOUNIDADEESTATISTICA { get; set; }
        public Nullable<decimal> VL_QUANTIDADE_ESTATISTICA { get; set; }
        public Nullable<decimal> VL_PESO_LIQUIDO { get; set; }
        public string STR_CODIGOCOMERCIALIZADA { get; set; }
        public Nullable<decimal> QT_COMERCIALIZACAO { get; set; }
        public Nullable<decimal> VL_CONDICAO_VENDA_REAL { get; set; }
        public Nullable<decimal> VL_COMISSAO_AGENTE { get; set; }
        public Nullable<decimal> VL_LOCAL_EMBARQUE { get; set; }
        public Nullable<decimal> PC_COMISSAO_AGENTE { get; set; }
        public string STR_CODIGOCONDICAOVENDA { get; set; }
        public Nullable<decimal> VL_CONDICAO_VENDA_ESTATISTICA { get; set; }
        public Nullable<decimal> VL_LOCAL_EMBARQUE_ESTATISTICA { get; set; }
        public string STR_CODIGOENQUADRAMENTO1 { get; set; }
        public string STR_CODIGOENQUADRAMENTO2 { get; set; }
        public string STR_CODIGOENQUADRAMENTO3 { get; set; }
        public string STR_CODIGOENQUADRAMENTO4 { get; set; }
        public string STR_CODIGOENQUADRAMENTO5 { get; set; }
        public string STR_CODIGOENQUADRAMENTO6 { get; set; }
        public Nullable<decimal> VL_DESCONTO { get; set; }
        public Nullable<System.DateTime> DT_CANCELADA { get; set; }
        public Nullable<int> CD_USUARIO_CANCELOU { get; set; }
        public Nullable<int> CD_PRODUTO { get; set; }
        public Nullable<decimal> VL_PRECO_UNITARIO_COMERCILIZACAO_CV { get; set; }
        public Nullable<decimal> VL_PRECO_UNITARIO_COMERCILIZACAO_LE { get; set; }
        public Nullable<decimal> VL_PRECO_UNITARIO_ESTATISTICA_CV { get; set; }
        public Nullable<decimal> VL_PRECO_UNITARIO_ESTATISTICA_LE { get; set; }
        public Nullable<decimal> VL_PRECO_UNITARIO_NOTA { get; set; }
        public string NR_CFOP { get; set; }
        public Nullable<decimal> VL_CONDICAO_VENDA_ATUAL { get; set; }
        public Nullable<decimal> VL_LOCAL_EMBARQUE_ATUAL { get; set; }
        public Nullable<decimal> VL_FINANCIAMENTO { get; set; }
        public Nullable<int> CD_DUE_NF_ITEM_ANT { get; set; }
        public Nullable<int> CD_NF_ITEM_ANTIGO { get; set; }
        public Nullable<decimal> VL_CONDICAO_VENDA_BRL { get; set; }
        public Nullable<bool> IC_ALTERADO { get; set; }
        public Nullable<int> QTD_NOTA_REFERENCIADA { get; set; }
        public Nullable<int> CD_SEQ_ITEM { get; set; }
        public string CD_PRODUTO2 { get; set; }
    
        public virtual DUE_NF DUE_NF { get; set; }
        public virtual DUE DUE { get; set; }
    }
}
