//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTIDADE
    {
        public ENTIDADE()
        {
            this.DDE = new HashSet<DDE>();
            this.DDE1 = new HashSet<DDE>();
            this.GRUPOCLI_ENTIDADE = new HashSet<GRUPOCLI_ENTIDADE>();
            this.PROCESSOS = new HashSet<PROCESSOS>();
            this.PROCESSOS1 = new HashSet<PROCESSOS>();
            this.PROCESSOS2 = new HashSet<PROCESSOS>();
            this.PROCESSOS3 = new HashSet<PROCESSOS>();
            this.PROCESSOS4 = new HashSet<PROCESSOS>();
            this.PROCESSOS5 = new HashSet<PROCESSOS>();
            this.PROCESSOS6 = new HashSet<PROCESSOS>();
            this.PROCESSOS7 = new HashSet<PROCESSOS>();
            this.PROCESSOS8 = new HashSet<PROCESSOS>();
            this.PROCESSOS9 = new HashSet<PROCESSOS>();
            this.PROCESSOS10 = new HashSet<PROCESSOS>();
            this.PROCESSOS11 = new HashSet<PROCESSOS>();
            this.RELACIONAMENTOENTIDADE = new HashSet<RELACIONAMENTOENTIDADE>();
            this.USUARIO_CA = new HashSet<USUARIO_CA>();
            this.RELAC_EXPORTADOR = new HashSet<RELAC_EXPORTADOR>();
            this.DUE = new HashSet<DUE>();
        }
    
        public int CD_ENTIDADE { get; set; }
        public string NM_ENTIDADE { get; set; }
        public string NM_FANTASIA_ENTIDADE { get; set; }
        public string NM_ENDERECO_ENTIDADE { get; set; }
        public string CD_ENDERECO_ENTIDADE { get; set; }
        public string DS_COMPLEMENTO_ENTIDADE { get; set; }
        public string CD_CEP_ENTIDADE { get; set; }
        public string NM_BAIRRO_ENTIDADE { get; set; }
        public Nullable<int> CD_UF_ENTIDADE { get; set; }
        public string CD_FAX_ENTIDADE { get; set; }
        public string CD_CPF_ENTIDADE { get; set; }
        public string CD_INSC_ESTADUAL_ENTIDADE { get; set; }
        public string IC_TIPO_PESSOA { get; set; }
        public string OBSERVACAO { get; set; }
        public string CD_RG_ENTIDADE { get; set; }
        public Nullable<int> CODCIDADE { get; set; }
        public string NM_CIDADE_ENTIDADE { get; set; }
        public string CD_CNPJ_ENTIDADE { get; set; }
        public string EMAIL_ENTIDADE { get; set; }
        public string CD_TEL_ENTIDADE { get; set; }
        public string CD_TELEFONE_CONTATO { get; set; }
        public string NM_PAIS_ENTIDADE { get; set; }
        public string NM_ESTADO_ENTIDADE { get; set; }
        public string NM_MOEDA_ENTIDADE { get; set; }
        public string NM_CIFRA_ENTIDADE { get; set; }
        public Nullable<System.DateTime> DT_ATUALIZACAO { get; set; }
        public Nullable<int> CD_EMPRESA { get; set; }
        public Nullable<int> CD_FILIAL { get; set; }
        public string CD_INSCR_MUNICIPAL_ENTIDADE { get; set; }
        public string CD_CEP_EXTERIOR { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public string ATIVO { get; set; }
        public string NM_CIDADE_EX { get; set; }
        public string NM_FANTASIA_MINERVA { get; set; }
        public Nullable<int> SG_AGENTE_DIRETO { get; set; }
        public Nullable<decimal> VL_PERCENT_DIRETOR_SDAS { get; set; }
        public Nullable<int> CD_DEPENDENTE_SDAS { get; set; }
        public Nullable<int> IC_GERAR_SDAS { get; set; }
        public string STR_CODIGORECIALFA { get; set; }
        public System.DateTime DT_CADASTRO { get; set; }
    
        public virtual ICollection<DDE> DDE { get; set; }
        public virtual ICollection<DDE> DDE1 { get; set; }
        public virtual ICollection<GRUPOCLI_ENTIDADE> GRUPOCLI_ENTIDADE { get; set; }
        public virtual ICollection<PROCESSOS> PROCESSOS { get; set; }
        public virtual ICollection<PROCESSOS> PROCESSOS1 { get; set; }
        public virtual ICollection<PROCESSOS> PROCESSOS2 { get; set; }
        public virtual ICollection<PROCESSOS> PROCESSOS3 { get; set; }
        public virtual ICollection<PROCESSOS> PROCESSOS4 { get; set; }
        public virtual ICollection<PROCESSOS> PROCESSOS5 { get; set; }
        public virtual ICollection<PROCESSOS> PROCESSOS6 { get; set; }
        public virtual ICollection<PROCESSOS> PROCESSOS7 { get; set; }
        public virtual ICollection<PROCESSOS> PROCESSOS8 { get; set; }
        public virtual ICollection<PROCESSOS> PROCESSOS9 { get; set; }
        public virtual ICollection<PROCESSOS> PROCESSOS10 { get; set; }
        public virtual ICollection<PROCESSOS> PROCESSOS11 { get; set; }
        public virtual ICollection<RELACIONAMENTOENTIDADE> RELACIONAMENTOENTIDADE { get; set; }
        public virtual ICollection<USUARIO_CA> USUARIO_CA { get; set; }
        public virtual ICollection<RELAC_EXPORTADOR> RELAC_EXPORTADOR { get; set; }
        public virtual ICollection<DUE> DUE { get; set; }
    }
}
