//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMA_EXPORTACAO_DUE
    {
        public string CD_FORMA_EXPORTACAO { get; set; }
        public string DS_FORMA_EXPORTACAO { get; set; }
    }
}
