//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPOCLI_TERMINAL_CONSULTA_USUARIO_DESTINATARIO
    {
        public int CD_USUARIO_CONSULTA_TERMINAL { get; set; }
        public Nullable<int> CD_GRUPO { get; set; }
        public Nullable<int> CD_USUARIO_DESTINATARIO { get; set; }
        public Nullable<int> CD_USUARIO { get; set; }
    }
}
