//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPOCLI_ENTIDADE
    {
        public int CD_GRUPOCLI_ENTIDADE { get; set; }
        public int CD_GRUPOCLI { get; set; }
        public int CD_ENTIDADE { get; set; }
        public Nullable<bool> SG_REMOVE_CLIENTE { get; set; }
        public string SG_TIPO { get; set; }
    
        public virtual GRUPOCLI GRUPOCLI { get; set; }
        public virtual ENTIDADE ENTIDADE { get; set; }
    }
}
