//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPOCLI
    {
        public GRUPOCLI()
        {
            this.GRUPOCLI_ENTIDADE = new HashSet<GRUPOCLI_ENTIDADE>();
        }
    
        public int CD_GRUPOCLI { get; set; }
        public string DS_GRUPOCLI { get; set; }
        public Nullable<bool> SG_ANALISTA { get; set; }
        public Nullable<int> CD_USUARIO { get; set; }
        public string SG_TRANSPORTE { get; set; }
        public string SG_SETOR { get; set; }
        public Nullable<bool> IC_RECEPCAO { get; set; }
        public Nullable<bool> IC_NUMERARIO_AUTOMATICO { get; set; }
        public string DS_EMAIL_GRUPO { get; set; }
        public Nullable<bool> IC_IA { get; set; }
        public string NM_ENDERECO_FTP { get; set; }
        public string NM_USUARIO_FTP { get; set; }
        public string NM_SENHA_FTP { get; set; }
        public string NM_PASTA_DESTINO_FTP { get; set; }
        public Nullable<bool> IC_ENVIA_EXTRATO_REGISTRADO_FTP { get; set; }
        public Nullable<bool> IC_ENVIA_EXTRATO_AVERBADO_FTP { get; set; }
        public Nullable<bool> IC_ENVIA_BL_FTP { get; set; }
        public Nullable<bool> IC_ENVIA_DOC_FINAL { get; set; }
        public Nullable<bool> IC_ENVIA_DOC_APROVACAO { get; set; }
        public Nullable<bool> IC_ENVIA_DOC_COPIA_BL { get; set; }
        public string ID_GUID { get; set; }
        public Nullable<bool> IC_ENVIA_DOC_FINAL_POR_EMAIL { get; set; }
        public string NM_ENVIA_DOC_FINAL_POR_EMAIL { get; set; }
        public string NM_USUARIO_WCF { get; set; }
        public string NM_SENHA_WCF { get; set; }
    
        public virtual ICollection<GRUPOCLI_ENTIDADE> GRUPOCLI_ENTIDADE { get; set; }
    }
}
