//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIST_CONSULTA_DEPOSITO
    {
        public int CD_CONSULTA_DEPOSITO { get; set; }
        public Nullable<System.DateTime> DT_CONSULTA_DEPOSITO { get; set; }
        public Nullable<int> CD_CLIENTE { get; set; }
    }
}
