//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCAIS
    {
        public LOCAIS()
        {
            this.PROCESSOS = new HashSet<PROCESSOS>();
        }
    
        public int CD_LOCAL { get; set; }
        public string STR_CODIGOPAIS { get; set; }
        public string CD_TRI_LOCAL { get; set; }
        public string NM_CIDADE { get; set; }
        public string CD_NUMERO_INTTRA { get; set; }
        public Nullable<int> CD_ESTADO { get; set; }
        public Nullable<System.DateTime> DT_CANCELADO { get; set; }
        public Nullable<int> CD_USUARIO_CANCELOU { get; set; }
        public Nullable<bool> IC_ORIGEM { get; set; }
        public Nullable<int> CD_CODIGO_MINERVA { get; set; }
        public string DS_EMAIL_OUTROS_PORTOS { get; set; }
        public Nullable<int> CD_GRUPO { get; set; }
        public string DS_SIGLA { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
    
        public virtual ICollection<PROCESSOS> PROCESSOS { get; set; }
    }
}
