//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_DIVERGENCIA_LACRE
    {
        public int CD_LOG { get; set; }
        public string NR_PROCESSO { get; set; }
        public Nullable<int> CD_CLIENTE { get; set; }
        public string DS_REFERENCIA { get; set; }
        public string NM_TERMINAL { get; set; }
        public string NR_BOOKING { get; set; }
        public string NR_CONTAINER { get; set; }
        public string DS_LACRE_AGENCIA { get; set; }
        public string DS_LACRE_AGENCIA_TERMINAL { get; set; }
        public string DS_LACRE_SIF { get; set; }
        public string DS_LACRE_SIF_TERMINAL { get; set; }
        public Nullable<System.DateTime> DT_LOG { get; set; }
    }
}
