//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_NOTIFICACAO_RECINTO
    {
        public int CD_LOG { get; set; }
        public Nullable<System.DateTime> DT_ENVIO { get; set; }
        public Nullable<int> CD_DUE { get; set; }
        public string STR_DESPACHO_ANT { get; set; }
        public string STR_DESPACHO { get; set; }
        public string STR_EMBARQUE_ANT { get; set; }
        public string STR_EMBARQUE { get; set; }
        public Nullable<int> CD_USUARIO { get; set; }
        public Nullable<bool> IC_ENVIADO { get; set; }
    }
}
