//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_ENVIO_MINERVA
    {
        public int CD_ENVIO_LOG { get; set; }
        public Nullable<System.DateTime> DT_LOG { get; set; }
        public string NR_ORDEM { get; set; }
        public Nullable<int> CD_PROCESSO { get; set; }
        public string NR_DUE { get; set; }
        public string NR_RUC { get; set; }
        public string NR_CHAVE_ACESSO { get; set; }
        public Nullable<System.DateTime> DT_REGISTRO { get; set; }
        public Nullable<int> COD_EMPRESA { get; set; }
        public Nullable<System.DateTime> DT_DESEMBARACO { get; set; }
        public Nullable<System.DateTime> DT_EMBARQUE { get; set; }
        public string NR_BL { get; set; }
        public string NR_LPCO { get; set; }
        public string DS_SISTEMA { get; set; }
        public Nullable<bool> SG_STATUS { get; set; }
        public string MSG_ERRO { get; set; }
        public string DS_TERMINAL_REDEX { get; set; }
        public string DS_TERMINAL_EMBARQUE { get; set; }
        public Nullable<System.DateTime> DT_TERMINAL_REDEX { get; set; }
        public Nullable<System.DateTime> DT_TERMINAL_EMBARQUE { get; set; }
        public Nullable<System.DateTime> DT_SAIDA_NAVIO { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_DRAFT { get; set; }
        public Nullable<System.DateTime> DT_CHEGADA_CSI { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_DOCS { get; set; }
        public string DS_ENVIO_DOCS { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_COURRIER { get; set; }
        public string NM_COURRIER { get; set; }
        public string NR_COURRIER { get; set; }
        public Nullable<System.DateTime> DT_AVERBADO { get; set; }
        public string NR_CSI { get; set; }
        public Nullable<System.DateTime> DT_BL_REAL { get; set; }
        public Nullable<System.DateTime> DT_ENVIADO { get; set; }
    }
}
