//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_CONSULTA_NAVIO
    {
        public int CD_INC { get; set; }
        public Nullable<int> CD_VIAGEM { get; set; }
        public string NR_VIAGEM { get; set; }
        public string NM_NAVIO { get; set; }
        public Nullable<System.DateTime> DT_CONSULTA { get; set; }
        public string NM_TERMINAL { get; set; }
        public string DS_STATUS { get; set; }
        public Nullable<System.DateTime> DT_ETA { get; set; }
        public Nullable<System.DateTime> DT_ETA_TERMINAL { get; set; }
        public Nullable<System.DateTime> DT_ATRACACAO_TERMINAL { get; set; }
        public Nullable<System.DateTime> DT_DESATRACACAO_TERMINAL { get; set; }
    }
}
