//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_CONSULTA_TERMINAL
    {
        public int CD_INC { get; set; }
        public Nullable<int> CD_PROCESSO { get; set; }
        public string NR_CONTAINER { get; set; }
        public Nullable<System.DateTime> DT_CONSULTA { get; set; }
        public string NM_TERMINAL { get; set; }
        public string DS_STATUS { get; set; }
        public string NR_BOOKING_TERMINAL { get; set; }
        public string NM_NAVIO_TERMINAL { get; set; }
        public string NR_DUE_TERMINAL { get; set; }
        public Nullable<System.DateTime> DT_PROTOCOLADO { get; set; }
        public Nullable<System.DateTime> DT_EMBARQUE { get; set; }
        public string NR_BOOKING { get; set; }
        public string NM_NAVIO { get; set; }
        public string NR_DUE { get; set; }
        public Nullable<System.DateTime> DT_DEPOSITO { get; set; }
    }
}
