//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class WEBSATELEntities : DbContext
    {
        public WEBSATELEntities()
            : base("name=WEBSATELEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PROCESSORESERVA> PROCESSORESERVA { get; set; }
        public DbSet<PROCESSOS> PROCESSOS { get; set; }
        public DbSet<RESERVAS> RESERVAS { get; set; }
        public DbSet<CONTAINER> CONTAINER { get; set; }
        public DbSet<LOCAIS> LOCAIS { get; set; }
        public DbSet<NAVIOS> NAVIOS { get; set; }
        public DbSet<STATUS_PROCESSO> STATUS_PROCESSO { get; set; }
        public DbSet<PROCESSOEVENTO> PROCESSOEVENTO { get; set; }
        public DbSet<PARAMETRO> PARAMETRO { get; set; }
        public DbSet<HIST_CONSULTA_DEPOSITO> HIST_CONSULTA_DEPOSITO { get; set; }
        public DbSet<GRUPOCLI> GRUPOCLI { get; set; }
        public DbSet<USUARIO_CA> USUARIO_CA { get; set; }
        public DbSet<GRUPOCLI_ENTIDADE> GRUPOCLI_ENTIDADE { get; set; }
        public DbSet<GRUPOCLI_TERMINAL_CONSULTA_USUARIO_DESTINATARIO> GRUPOCLI_TERMINAL_CONSULTA_USUARIO_DESTINATARIO { get; set; }
        public DbSet<DUE> DUE { get; set; }
        public DbSet<PROCESSO_LOTE> PROCESSO_LOTE { get; set; }
        public DbSet<UNIDRF> UNIDRF { get; set; }
        public DbSet<RECIALFA> RECIALFA { get; set; }
        public DbSet<FORMA_EXPORTACAO_DUE> FORMA_EXPORTACAO_DUE { get; set; }
        public DbSet<PRE_PROCESSOS> PRE_PROCESSOS { get; set; }
        public DbSet<AVISOS_PRE_PROCESSO> AVISOS_PRE_PROCESSO { get; set; }
        public DbSet<DDE> DDE { get; set; }
        public DbSet<VIAGEM> VIAGEM { get; set; }
        public DbSet<LOG_CONSULTA_TERMINAL> LOG_CONSULTA_TERMINAL { get; set; }
        public DbSet<PAIS> PAIS { get; set; }
        public DbSet<VIAGEMARMADOR> VIAGEMARMADOR { get; set; }
        public DbSet<RELACIONAMENTOENTIDADE> RELACIONAMENTOENTIDADE { get; set; }
        public DbSet<ENTIDADE> ENTIDADE { get; set; }
        public DbSet<LOG_NOTIFICACAO_RECINTO> LOG_NOTIFICACAO_RECINTO { get; set; }
        public DbSet<DUE_NF_ITEM> DUE_NF_ITEM { get; set; }
        public DbSet<LOG_ENVIO_MINERVA> LOG_ENVIO_MINERVA { get; set; }
        public DbSet<DUE_NF> DUE_NF { get; set; }
        public DbSet<LOG_CONSULTA_NAVIO> LOG_CONSULTA_NAVIO { get; set; }
        public DbSet<TMP_CONSULTA_NAVIO> TMP_CONSULTA_NAVIO { get; set; }
        public DbSet<RELAC_EXPORTADOR> RELAC_EXPORTADOR { get; set; }
        public DbSet<TMP_CONSULTA_EMBARQUE> TMP_CONSULTA_EMBARQUE { get; set; }
        public DbSet<PROCESSORESERVACONTAINER> PROCESSORESERVACONTAINER { get; set; }
        public DbSet<LOG_DIVERGENCIA_LACRE> LOG_DIVERGENCIA_LACRE { get; set; }
        public DbSet<BTP_IMPORTAR_EXCEL> BTP_IMPORTAR_EXCEL { get; set; }
        public DbSet<PARAMETRO_WEB> PARAMETRO_WEB { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SP_RETORNA_TERMINAL_DUE(Nullable<int> cD_PROCESSORESERVA)
        {
            var cD_PROCESSORESERVAParameter = cD_PROCESSORESERVA.HasValue ?
                new ObjectParameter("CD_PROCESSORESERVA", cD_PROCESSORESERVA) :
                new ObjectParameter("CD_PROCESSORESERVA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_RETORNA_TERMINAL_DUE", cD_PROCESSORESERVAParameter);
        }
    
        public virtual int SP_ATUALIZA_STATUS_CONTAINER(Nullable<int> cD_PROCESSORESERVACONTAINER, Nullable<int> cD_CONTAINER)
        {
            var cD_PROCESSORESERVACONTAINERParameter = cD_PROCESSORESERVACONTAINER.HasValue ?
                new ObjectParameter("CD_PROCESSORESERVACONTAINER", cD_PROCESSORESERVACONTAINER) :
                new ObjectParameter("CD_PROCESSORESERVACONTAINER", typeof(int));
    
            var cD_CONTAINERParameter = cD_CONTAINER.HasValue ?
                new ObjectParameter("CD_CONTAINER", cD_CONTAINER) :
                new ObjectParameter("CD_CONTAINER", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ATUALIZA_STATUS_CONTAINER", cD_PROCESSORESERVACONTAINERParameter, cD_CONTAINERParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_CONSULTA_CONTAINERS_EMBARQUE_Result> SP_SELECT_CONSULTA_CONTAINERS_EMBARQUE(Nullable<int> cD_TERMINAL, string nR_CONTAINER)
        {
            var cD_TERMINALParameter = cD_TERMINAL.HasValue ?
                new ObjectParameter("CD_TERMINAL", cD_TERMINAL) :
                new ObjectParameter("CD_TERMINAL", typeof(int));
    
            var nR_CONTAINERParameter = nR_CONTAINER != null ?
                new ObjectParameter("NR_CONTAINER", nR_CONTAINER) :
                new ObjectParameter("NR_CONTAINER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_CONSULTA_CONTAINERS_EMBARQUE_Result>("SP_SELECT_CONSULTA_CONTAINERS_EMBARQUE", cD_TERMINALParameter, nR_CONTAINERParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_CONSULTA_CONTAINERS_TERMINAL_Result> SP_SELECT_CONSULTA_CONTAINERS_TERMINAL(string nR_CONTAINER, Nullable<int> cD_TERMINAL)
        {
            var nR_CONTAINERParameter = nR_CONTAINER != null ?
                new ObjectParameter("NR_CONTAINER", nR_CONTAINER) :
                new ObjectParameter("NR_CONTAINER", typeof(string));
    
            var cD_TERMINALParameter = cD_TERMINAL.HasValue ?
                new ObjectParameter("CD_TERMINAL", cD_TERMINAL) :
                new ObjectParameter("CD_TERMINAL", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_CONSULTA_CONTAINERS_TERMINAL_Result>("SP_SELECT_CONSULTA_CONTAINERS_TERMINAL", nR_CONTAINERParameter, cD_TERMINALParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_CONSULTA_LACRES_TERMINAL_Result> SP_SELECT_CONSULTA_LACRES_TERMINAL(Nullable<int> cD_TERMINAL, string nR_CONTAINER)
        {
            var cD_TERMINALParameter = cD_TERMINAL.HasValue ?
                new ObjectParameter("CD_TERMINAL", cD_TERMINAL) :
                new ObjectParameter("CD_TERMINAL", typeof(int));
    
            var nR_CONTAINERParameter = nR_CONTAINER != null ?
                new ObjectParameter("NR_CONTAINER", nR_CONTAINER) :
                new ObjectParameter("NR_CONTAINER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_CONSULTA_LACRES_TERMINAL_Result>("SP_SELECT_CONSULTA_LACRES_TERMINAL", cD_TERMINALParameter, nR_CONTAINERParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_CONSULTA_CONTAINERS_Result> SP_SELECT_CONSULTA_CONTAINERS(Nullable<int> cD_TERMINAL, string nR_CONTAINER, Nullable<bool> iC_CONFIRMACAO)
        {
            var cD_TERMINALParameter = cD_TERMINAL.HasValue ?
                new ObjectParameter("CD_TERMINAL", cD_TERMINAL) :
                new ObjectParameter("CD_TERMINAL", typeof(int));
    
            var nR_CONTAINERParameter = nR_CONTAINER != null ?
                new ObjectParameter("NR_CONTAINER", nR_CONTAINER) :
                new ObjectParameter("NR_CONTAINER", typeof(string));
    
            var iC_CONFIRMACAOParameter = iC_CONFIRMACAO.HasValue ?
                new ObjectParameter("IC_CONFIRMACAO", iC_CONFIRMACAO) :
                new ObjectParameter("IC_CONFIRMACAO", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_CONSULTA_CONTAINERS_Result>("SP_SELECT_CONSULTA_CONTAINERS", cD_TERMINALParameter, nR_CONTAINERParameter, iC_CONFIRMACAOParameter);
        }
    
        public virtual ObjectResult<SP_CONSULTA_DEPOSITO_USUARIO_Result> SP_CONSULTA_DEPOSITO_USUARIO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONSULTA_DEPOSITO_USUARIO_Result>("SP_CONSULTA_DEPOSITO_USUARIO");
        }
    
        public virtual ObjectResult<SP_SELECT_CONSULTA_CONTAINERS_CLIENTE_Result> SP_SELECT_CONSULTA_CONTAINERS_CLIENTE(Nullable<int> cD_TERMINAL, string nR_CONTAINER, Nullable<bool> iC_CONFIRMACAO, string cD_GRUPO, string cD_GRUPO_NAO)
        {
            var cD_TERMINALParameter = cD_TERMINAL.HasValue ?
                new ObjectParameter("CD_TERMINAL", cD_TERMINAL) :
                new ObjectParameter("CD_TERMINAL", typeof(int));
    
            var nR_CONTAINERParameter = nR_CONTAINER != null ?
                new ObjectParameter("NR_CONTAINER", nR_CONTAINER) :
                new ObjectParameter("NR_CONTAINER", typeof(string));
    
            var iC_CONFIRMACAOParameter = iC_CONFIRMACAO.HasValue ?
                new ObjectParameter("IC_CONFIRMACAO", iC_CONFIRMACAO) :
                new ObjectParameter("IC_CONFIRMACAO", typeof(bool));
    
            var cD_GRUPOParameter = cD_GRUPO != null ?
                new ObjectParameter("CD_GRUPO", cD_GRUPO) :
                new ObjectParameter("CD_GRUPO", typeof(string));
    
            var cD_GRUPO_NAOParameter = cD_GRUPO_NAO != null ?
                new ObjectParameter("CD_GRUPO_NAO", cD_GRUPO_NAO) :
                new ObjectParameter("CD_GRUPO_NAO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_CONSULTA_CONTAINERS_CLIENTE_Result>("SP_SELECT_CONSULTA_CONTAINERS_CLIENTE", cD_TERMINALParameter, nR_CONTAINERParameter, iC_CONFIRMACAOParameter, cD_GRUPOParameter, cD_GRUPO_NAOParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_CONSULTA_CONTAINERS_EMBARQUE_CLIENTE_Result> SP_SELECT_CONSULTA_CONTAINERS_EMBARQUE_CLIENTE(Nullable<int> cD_TERMINAL, string nR_CONTAINER, string cD_GRUPO, string cD_GRUPO_NAO)
        {
            var cD_TERMINALParameter = cD_TERMINAL.HasValue ?
                new ObjectParameter("CD_TERMINAL", cD_TERMINAL) :
                new ObjectParameter("CD_TERMINAL", typeof(int));
    
            var nR_CONTAINERParameter = nR_CONTAINER != null ?
                new ObjectParameter("NR_CONTAINER", nR_CONTAINER) :
                new ObjectParameter("NR_CONTAINER", typeof(string));
    
            var cD_GRUPOParameter = cD_GRUPO != null ?
                new ObjectParameter("CD_GRUPO", cD_GRUPO) :
                new ObjectParameter("CD_GRUPO", typeof(string));
    
            var cD_GRUPO_NAOParameter = cD_GRUPO_NAO != null ?
                new ObjectParameter("CD_GRUPO_NAO", cD_GRUPO_NAO) :
                new ObjectParameter("CD_GRUPO_NAO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_CONSULTA_CONTAINERS_EMBARQUE_CLIENTE_Result>("SP_SELECT_CONSULTA_CONTAINERS_EMBARQUE_CLIENTE", cD_TERMINALParameter, nR_CONTAINERParameter, cD_GRUPOParameter, cD_GRUPO_NAOParameter);
        }
    
        public virtual ObjectResult<SP_SELECT_CONSULTA_CONTAINERS_TERMINAL_CLIENTE_Result> SP_SELECT_CONSULTA_CONTAINERS_TERMINAL_CLIENTE(string nR_CONTAINER, Nullable<int> cD_TERMINAL, string cD_GRUPO, string cD_GRUPO_NAO)
        {
            var nR_CONTAINERParameter = nR_CONTAINER != null ?
                new ObjectParameter("NR_CONTAINER", nR_CONTAINER) :
                new ObjectParameter("NR_CONTAINER", typeof(string));
    
            var cD_TERMINALParameter = cD_TERMINAL.HasValue ?
                new ObjectParameter("CD_TERMINAL", cD_TERMINAL) :
                new ObjectParameter("CD_TERMINAL", typeof(int));
    
            var cD_GRUPOParameter = cD_GRUPO != null ?
                new ObjectParameter("CD_GRUPO", cD_GRUPO) :
                new ObjectParameter("CD_GRUPO", typeof(string));
    
            var cD_GRUPO_NAOParameter = cD_GRUPO_NAO != null ?
                new ObjectParameter("CD_GRUPO_NAO", cD_GRUPO_NAO) :
                new ObjectParameter("CD_GRUPO_NAO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SELECT_CONSULTA_CONTAINERS_TERMINAL_CLIENTE_Result>("SP_SELECT_CONSULTA_CONTAINERS_TERMINAL_CLIENTE", nR_CONTAINERParameter, cD_TERMINALParameter, cD_GRUPOParameter, cD_GRUPO_NAOParameter);
        }
    
        public virtual ObjectResult<SP_CONSULTA_DEPOSITO_USUARIO_IC_ROBO_Result> SP_CONSULTA_DEPOSITO_USUARIO_IC_ROBO(Nullable<int> iC_ROBO)
        {
            var iC_ROBOParameter = iC_ROBO.HasValue ?
                new ObjectParameter("IC_ROBO", iC_ROBO) :
                new ObjectParameter("IC_ROBO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONSULTA_DEPOSITO_USUARIO_IC_ROBO_Result>("SP_CONSULTA_DEPOSITO_USUARIO_IC_ROBO", iC_ROBOParameter);
        }
    }
}
