//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAVIOS
    {
        public int CD_NAVIO { get; set; }
        public string NM_NAVIO { get; set; }
        public Nullable<int> CD_ARMADOR { get; set; }
        public string CD_LOYD_REGISTER { get; set; }
        public string DS_OBSERVACAO { get; set; }
        public Nullable<int> CD_EMPRESA { get; set; }
        public Nullable<int> CD_FILIAL { get; set; }
        public Nullable<System.DateTime> DT_CANCELADO { get; set; }
    }
}
