//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAIS
    {
        public int CD_PAIS { get; set; }
        public string STR_CODIGOPAIS { get; set; }
        public string STR_NACIONALIDADE { get; set; }
        public string STR_NOMEPAIS { get; set; }
        public string STR_NOMEPAISINGLES { get; set; }
        public string STR_SIGLA { get; set; }
        public string STR_CONTINENTE { get; set; }
        public string STR_CODIGOREGIAO { get; set; }
        public string STR_CODIGONOIMPORTADOR { get; set; }
        public string STR_CODIGOEXTERNO { get; set; }
        public string STR_CODIGOPAISFIESP { get; set; }
        public string STR_CODIGOPAISSISCO { get; set; }
        public Nullable<int> CD_BACEM { get; set; }
        public Nullable<int> NM_ID { get; set; }
        public string FL_FOMIGACAO { get; set; }
        public string FL_DESINFECCAO { get; set; }
        public Nullable<decimal> NR_LIMITE_PESO_CC20 { get; set; }
        public Nullable<decimal> NR_LIMITE_PESO_CC40 { get; set; }
        public Nullable<int> CD_ENTIDADE { get; set; }
        public Nullable<int> CD_FILIAL { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public string NM_PAIS { get; set; }
        public string STR_CODIGO_ISO { get; set; }
        public string STR_CODIGOPAIS_DUE { get; set; }
        public Nullable<int> CD_PAIS_MINERVA { get; set; }
        public Nullable<int> CD_GRUPO { get; set; }
        public Nullable<bool> IC_LEGALIZADO { get; set; }
        public Nullable<int> IC_MERCOSUL { get; set; }
    }
}
