//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARAMETRO_WEB
    {
        public int CD_PARAMETRO_WEB { get; set; }
        public string NM_PARAMETRO_WEB { get; set; }
        public string NM_DISPLAY { get; set; }
        public string VR_PARAMETRO_WEB { get; set; }
        public Nullable<bool> IC_VISUALIZAR { get; set; }
        public string SG_MODULO { get; set; }
    }
}
