//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_PROCESSOS
    {
        public int CD_PROCESSO { get; set; }
        public string NR_ORDEM { get; set; }
        public string NR_ORDEM_LOTE { get; set; }
        public Nullable<int> CD_PROCESSO_PAI { get; set; }
        public string IC_TIPO { get; set; }
        public string IC_TIPO_ORDEM_LOTE { get; set; }
        public string IC_VIA_TRANSPORTE { get; set; }
        public string OBS_ALTERACAO { get; set; }
        public string EMBARCADOR_NOME { get; set; }
        public string EMBARCADOR_CNPJ { get; set; }
        public string EMBARCADOR_ENDERECO { get; set; }
        public string EMBARCADOR_NUMERO { get; set; }
        public string EMBARCADOR_COMPLEMENTO { get; set; }
        public string EMBARCADOR_CIDADE { get; set; }
        public string EMBARCADOR_BAIRRO { get; set; }
        public string EMBARCADOR_ESTADO { get; set; }
        public string EMBARCADOR_PAIS { get; set; }
        public string EMBARCADOR_OBS { get; set; }
        public Nullable<int> IMPORTADOR_CODIGO { get; set; }
        public string IMPORTADOR_NOME { get; set; }
        public string IMPORTADOR_ENDERECO { get; set; }
        public string IMPORTADOR_NUMERO { get; set; }
        public string IMPORTADOR_COMPLEMENTO { get; set; }
        public string IMPORTADOR_CIDADE { get; set; }
        public string IMPORTADOR_ESTADO { get; set; }
        public string IMPORTADOR_PAIS { get; set; }
        public string IMPORTADOR_OBS { get; set; }
        public Nullable<int> CONSIGNATARIO_CODIGO { get; set; }
        public string CONSIGNATARIO_NOME { get; set; }
        public string CONSIGNATARIO_ENDERECO { get; set; }
        public string CONSIGNATARIO_NUMERO { get; set; }
        public string CONSIGNATARIO_COMPLEMENTO { get; set; }
        public string CONSIGNATARIO_CIDADE { get; set; }
        public string CONSIGNATARIO_ESTADO { get; set; }
        public string CONSIGNATARIO_PAIS { get; set; }
        public string CONSIGNATARIO_OBS { get; set; }
        public Nullable<int> NOTIFY_CODIGO { get; set; }
        public string NOTIFY_NOME { get; set; }
        public string NOTIFY_ENDERECO { get; set; }
        public string NOTIFY_NUMERO { get; set; }
        public string NOTIFY_COMPLEMENTO { get; set; }
        public string NOTIFY_CIDADE { get; set; }
        public string NOTIFY_ESTADO { get; set; }
        public string NOTIFY_PAIS { get; set; }
        public string NOTIFY_OBS { get; set; }
        public Nullable<decimal> COMISSIONADO_PERCENTUAL { get; set; }
        public string TRANSPORTADOR_CNPJ { get; set; }
        public string TRANSPORTADOR_NOME { get; set; }
        public string TRANSPORTADOR_ENDERECO { get; set; }
        public string TRANSPORTADOR_NUMERO { get; set; }
        public string TRANSPORTADOR_COMPLEMENTO { get; set; }
        public string TRANSPORTADOR_CIDADE { get; set; }
        public string TRANSPORTADOR_BAIRRO { get; set; }
        public string TRANSPORTADOR_ESTADO { get; set; }
        public string TRANSPORTADOR_PAIS { get; set; }
        public string TRANSPORTADOR_OBS { get; set; }
        public string PLACA_VEICULO_LOCAL { get; set; }
        public string PORTO_ORIGEM { get; set; }
        public string PORTO_DESTINO { get; set; }
        public string PORTO_TRANSITO { get; set; }
        public Nullable<int> CODIGO_VEICULO { get; set; }
        public string NOME_VEICULO { get; set; }
        public Nullable<int> CODIGO_TERMINAL { get; set; }
        public string NOME_TERMINAL { get; set; }
        public string NUMERO_RESERVA { get; set; }
        public string NUMERO_CONTAINER { get; set; }
        public string NUMERO_VOO { get; set; }
        public string NUMERO_AWB { get; set; }
        public Nullable<decimal> TARA_CONTAINER { get; set; }
        public string LACRE_AGENCIA { get; set; }
        public Nullable<decimal> VALOR_FRETE { get; set; }
        public Nullable<System.DateTime> DEADLINE_DRAFT { get; set; }
        public Nullable<System.DateTime> DEADLINE_EMBARQUE { get; set; }
        public Nullable<System.DateTime> DT_ETA { get; set; }
        public Nullable<System.DateTime> DT_ETD { get; set; }
        public string NUMERO_NF { get; set; }
        public string LACRE_SIF { get; set; }
        public string NR_CERTIFICADO_ORIGEM { get; set; }
        public string NR_TEMPERATURA { get; set; }
        public string DELIVERY_TERM { get; set; }
        public string NM_PRODUTO_GENERICO { get; set; }
        public Nullable<System.DateTime> DT_PRODUCAO_INICIO { get; set; }
        public Nullable<System.DateTime> DT_PRODUCAO_TERMINO { get; set; }
        public Nullable<System.DateTime> DT_EMBALAGEM_INICIO { get; set; }
        public Nullable<System.DateTime> DT_EMBALAGEM_TERMINO { get; set; }
        public Nullable<System.DateTime> DT_VALIDADE_INICIO { get; set; }
        public Nullable<System.DateTime> DT_VALIDADE_TERMINO { get; set; }
        public string SG_MODALIDADE_FRETE { get; set; }
        public string SG_MOEDA { get; set; }
        public Nullable<decimal> VL_CRF { get; set; }
        public Nullable<decimal> VL_FRETE { get; set; }
        public Nullable<decimal> VL_FOB { get; set; }
        public Nullable<decimal> VL_DESCONTO { get; set; }
        public string DS_CAMINHO_INSTRUCAO { get; set; }
        public string DS_CAMINHO_NOTA { get; set; }
        public Nullable<int> IC_STATUS { get; set; }
        public Nullable<System.DateTime> DT_ENVIO { get; set; }
        public string ARMADOR_CNPJ { get; set; }
        public string ARMADOR_NOME { get; set; }
        public string ARMADOR_ENDERECO { get; set; }
        public string ARMADOR_NUMERO { get; set; }
        public string ARMADOR_COMPLEMENTO { get; set; }
        public string ARMADOR_CIDADE { get; set; }
        public string ARMADOR_BAIRRO { get; set; }
        public string ARMADOR_ESTADO { get; set; }
        public string ARMADOR_PAIS { get; set; }
        public string ARMADOR_OBS { get; set; }
        public string OBS_PROCESSO { get; set; }
        public string OBS_BL { get; set; }
        public Nullable<int> CD_PROCESSO_REAL { get; set; }
        public string CD_NUMERO_PROCESSO { get; set; }
        public Nullable<int> SG_STATUS { get; set; }
        public Nullable<int> QTD_ORDEM_LOTE { get; set; }
        public Nullable<int> COD_EMPRESA { get; set; }
        public Nullable<System.DateTime> DT_PROCESSO { get; set; }
        public Nullable<int> IMPORTADOR_CODIGOPAIS { get; set; }
        public Nullable<int> CONSIGNATARIO_CODIGOPAIS { get; set; }
        public Nullable<int> NOTIFY_CODIGOPAIS { get; set; }
        public Nullable<bool> IC_ADVERTENCIA { get; set; }
        public Nullable<System.DateTime> DT_CANCELAMENTO { get; set; }
        public string TERMINAL_NOME { get; set; }
        public string TERMINAL_CNPJ { get; set; }
        public string TERMINAL_ENDERECO { get; set; }
        public string TERMINAL_NUMERO { get; set; }
        public string TERMINAL_COMPLEMENTO { get; set; }
        public string TERMINAL_CIDADE { get; set; }
        public string TERMINAL_BAIRRO { get; set; }
        public string TERMINAL_ESTADO { get; set; }
        public string TERMINAL_PAIS { get; set; }
        public Nullable<int> TERMINAL_CODIGOPAIS { get; set; }
        public Nullable<int> CD_PORTO_ORIGEM { get; set; }
        public Nullable<int> CD_PORTO_DESTINO { get; set; }
        public Nullable<int> CD_PORTO_TRANSITO { get; set; }
        public Nullable<int> CD_PAIS_TRANSPORTADORA { get; set; }
        public Nullable<int> CD_GRUPO { get; set; }
        public string NR_CHAVE_NF { get; set; }
        public string DS_TERMO_PAGTO { get; set; }
        public string DS_TIPO_FRETE { get; set; }
        public string DS_COMPLEMENTO_INCOTERM { get; set; }
        public string DS_BANCO_CLIENTE { get; set; }
        public Nullable<decimal> VL_ADIANTAMENTO { get; set; }
        public Nullable<decimal> VL_ADICIONAL_CAMBIO { get; set; }
        public string CONSIGNATARIO_OBS_CAMBIO { get; set; }
        public Nullable<bool> IC_TEM_DESCRICAO_UNICA_CAMBIO { get; set; }
        public string DS_DESCRICAO_UNICA_CAMBIO { get; set; }
        public string DS_MARCACAO_CORPO_BL { get; set; }
        public string DS_MARCAS_BL { get; set; }
        public string DS_NUMERO_CERT_SANITARIO { get; set; }
        public Nullable<bool> IC_HC_CORPO_BL { get; set; }
        public string DS_COMENTARIOS_BL { get; set; }
        public string SG_TIPO_FRETE_BL { get; set; }
        public string SG_FRETE_PAYABLE { get; set; }
        public string DS_FRETE_PAYABLE { get; set; }
        public Nullable<int> CD_LOCAL_FRETE_PAYABLE { get; set; }
        public string NM_LOCAL_FRETE_PAYABLE { get; set; }
        public Nullable<int> CD_PORTO_PLACE_OFDELIVERY { get; set; }
        public string NM_PORTO_PLACE_OFDELIVERY { get; set; }
        public string DS_OBS_FATURA_COMERCIAL { get; set; }
        public string DS_LOCAL_ABATE { get; set; }
        public string DS_LOCAL_PRODUCAO { get; set; }
        public string DS_OBS_DOCUMENTACAO { get; set; }
        public Nullable<int> CD_PAIS_DESTINO_FINAL { get; set; }
        public string NM_PAIS_DESTINO_FINAL { get; set; }
        public Nullable<System.DateTime> DT_SUSPENSO { get; set; }
        public string PRE_PAGAMENTO { get; set; }
        public string SHIPPING_MARK { get; set; }
    }
}
