//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSO_LOTE
    {
        public int CD_PROCESSO_LOTE { get; set; }
        public Nullable<int> CD_PROCESSO_MASTER { get; set; }
        public Nullable<int> CD_PROCESSO_FILHO { get; set; }
        public Nullable<int> CD_DUE { get; set; }
        public Nullable<int> CD_BL { get; set; }
        public string IC_TIPO { get; set; }
    
        public virtual PROCESSOS PROCESSOS { get; set; }
        public virtual PROCESSOS PROCESSOS1 { get; set; }
        public virtual DUE DUE { get; set; }
    }
}
