//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSORESERVA
    {
        public PROCESSORESERVA()
        {
            this.PROCESSORESERVACONTAINER = new HashSet<PROCESSORESERVACONTAINER>();
        }
    
        public int CD_PROCESSORESERVA { get; set; }
        public int CD_PROCESSO { get; set; }
        public int CD_RESERVA { get; set; }
        public Nullable<System.DateTime> DT_DEAD_LINE_DRAFT { get; set; }
        public Nullable<System.DateTime> DT_DEAD_LINE_CONTAINER { get; set; }
        public Nullable<System.DateTime> DT_DEAD_LINE_DOCUMENTACAO { get; set; }
        public Nullable<int> QTD_CONTAINER_RESERVA { get; set; }
    
        public virtual PROCESSOS PROCESSOS { get; set; }
        public virtual RESERVAS RESERVAS { get; set; }
        public virtual ICollection<PROCESSORESERVACONTAINER> PROCESSORESERVACONTAINER { get; set; }
    }
}
