//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSORESERVACONTAINER
    {
        public int CD_PROCESSORESERVACONTAINER { get; set; }
        public int CD_PROCESSORESERVA { get; set; }
        public int CD_CONTAINER { get; set; }
        public Nullable<int> CD_TERMINAL_REDEX { get; set; }
        public Nullable<System.DateTime> DT_REDEX { get; set; }
        public Nullable<System.DateTime> DT_DEPOSITO_TERM_EMBARQUE { get; set; }
        public Nullable<System.DateTime> DT_CHEGADA_NF { get; set; }
        public Nullable<System.DateTime> DT_CHEGADA_CSI { get; set; }
        public Nullable<System.DateTime> DT_PRESENCA_CARGA { get; set; }
        public Nullable<System.DateTime> DT_ENTRADA_TF { get; set; }
        public Nullable<System.DateTime> DT_EMBARQUE { get; set; }
        public Nullable<int> CD_STATUS_CONTAINER { get; set; }
        public Nullable<int> CD_TRANSPORTADORA { get; set; }
        public Nullable<int> CD_STATUS_CONTAINER2 { get; set; }
        public string NR_CSI { get; set; }
        public Nullable<int> CD_STATUS_DOCUMENTAL { get; set; }
        public Nullable<System.DateTime> DT_DESPACHO_PROTOCOLADO { get; set; }
        public Nullable<int> NR_ORDEM_CONTAINER { get; set; }
        public string IC_CONFERENCIA_FISICA { get; set; }
        public Nullable<System.DateTime> DT_CONFERENCIA_FISICA { get; set; }
        public Nullable<int> CD_ARMAZEM { get; set; }
        public string NR_LPCO { get; set; }
        public string IC_SITUACAO_LPCO { get; set; }
        public Nullable<System.DateTime> DT_REGISTRO_LPCO { get; set; }
        public Nullable<System.DateTime> DT_SITUACAO_DEFERIDO { get; set; }
        public Nullable<System.DateTime> DT_EXIGENCIA { get; set; }
        public Nullable<System.DateTime> DT_CANCELADO { get; set; }
        public Nullable<System.DateTime> DT_ESGOTADO { get; set; }
        public Nullable<System.DateTime> DT_RESPOSTA_EXIGENCIA { get; set; }
        public Nullable<System.DateTime> DT_ANULADO_REVOGADO { get; set; }
        public Nullable<System.DateTime> DT_EM_VERIFICACAO { get; set; }
        public Nullable<System.DateTime> DT_EM_INSPECAO { get; set; }
        public Nullable<System.DateTime> DT_VENCIDO { get; set; }
        public Nullable<System.DateTime> DT_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_SITUACAO_INDEFERIDO { get; set; }
        public Nullable<System.DateTime> DT_EM_EXIGENCIA { get; set; }
        public string NR_ORDDEM_CLIENTE { get; set; }
        public Nullable<bool> IC_CSI_IMPORTADOR { get; set; }
        public Nullable<bool> IC_NR_CSI_VALIDO { get; set; }
        public string NR_PARECER_CSI { get; set; }
        public Nullable<bool> IC_CSI_CONSULTADO { get; set; }
        public Nullable<bool> IC_LACRES_CONFERIDOS { get; set; }
        public Nullable<System.DateTime> DT_CSI { get; set; }
    
        public virtual CONTAINER CONTAINER { get; set; }
        public virtual PROCESSORESERVA PROCESSORESERVA { get; set; }
    }
}
