//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSOEVENTO
    {
        public int CD_PROCESSOEVENTO { get; set; }
        public Nullable<int> CD_PROCESSO { get; set; }
        public Nullable<int> CD_EVENTO { get; set; }
        public string DS_COMPLEMENTO { get; set; }
        public Nullable<int> CD_ITEM { get; set; }
        public Nullable<decimal> VL_PROCESSOEVENTO { get; set; }
        public Nullable<System.DateTime> DT_PROCESSOEVENTO { get; set; }
        public Nullable<bool> IC_APLICAVEL { get; set; }
        public Nullable<System.DateTime> DT_LANCAMENTO_PROCESSOEVENTO { get; set; }
        public Nullable<bool> IC_EXIBE_CLIENTE { get; set; }
        public Nullable<int> CD_USUARIO { get; set; }
        public string DS_OBS { get; set; }
        public Nullable<bool> IC_CLIENTE { get; set; }
    
        public virtual PROCESSOS PROCESSOS { get; set; }
    }
}
