//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSOS
    {
        public PROCESSOS()
        {
            this.PROCESSORESERVA = new HashSet<PROCESSORESERVA>();
            this.PROCESSOEVENTO = new HashSet<PROCESSOEVENTO>();
            this.PROCESSO_LOTE = new HashSet<PROCESSO_LOTE>();
            this.PROCESSO_LOTE1 = new HashSet<PROCESSO_LOTE>();
            this.DDE = new HashSet<DDE>();
            this.DUE = new HashSet<DUE>();
        }
    
        public int CD_PROCESSO { get; set; }
        public int CD_UNIDADE_NEGOCIO { get; set; }
        public string IC_PROCESSO { get; set; }
        public string CD_NUMERO_PROCESSO { get; set; }
        public Nullable<System.DateTime> DT_PEDIDO { get; set; }
        public System.DateTime DT_PEDIDO_INSERCAO { get; set; }
        public int CD_CLIENTE { get; set; }
        public string DS_REFERENCIA_CLIENTE { get; set; }
        public string DS_COMPLEMENTO_CLIENTE { get; set; }
        public Nullable<int> CD_IMPORTADOR { get; set; }
        public string STR_CODIGOVIATRANSPORTE { get; set; }
        public string STR_CODIGOINCOTERM { get; set; }
        public string SG_MODALIDADE_FRETE { get; set; }
        public Nullable<decimal> VL_FRETE { get; set; }
        public string QT_CONTAINERS { get; set; }
        public string NM_FATURA { get; set; }
        public Nullable<bool> IC_FRETE_INTER_EMBUTIDO { get; set; }
        public Nullable<decimal> VL_DESCONTO { get; set; }
        public string SG_IDIOMA { get; set; }
        public string DS_EXPORTADOR { get; set; }
        public Nullable<int> CD_REPRESENTANTE_CAMBIO { get; set; }
        public Nullable<int> CD_AGENTE_ARMADOR { get; set; }
        public string STR_CODIGOTERMOPGTO_CAMBIO { get; set; }
        public Nullable<int> CD_SHIPPER { get; set; }
        public Nullable<int> CD_CONSIGNATARIO { get; set; }
        public string DS_CONSIGNATARIO { get; set; }
        public Nullable<int> CD_NOTIFY { get; set; }
        public string DS_NOTIFY { get; set; }
        public Nullable<int> CD_ALSONOTIFY { get; set; }
        public string DS_ALSONOTIFY { get; set; }
        public string DS_MERCADORIA_CAMBIO { get; set; }
        public string DS_MARCAS_CAMBIO { get; set; }
        public string DS_LOCAL_ABATE { get; set; }
        public string DS_LOCAL_PRODUCAO { get; set; }
        public string DS_DATA_ABATE { get; set; }
        public string DS_DATA_PRODUCAO { get; set; }
        public string DS_DATA_VALIDADE { get; set; }
        public string DS_TERMO_PAGAMENTO_CAMBIO { get; set; }
        public string DS_PROTOCOLO { get; set; }
        public Nullable<System.DateTime> DT_ENTRADA { get; set; }
        public Nullable<System.DateTime> DT_LIBERACAO { get; set; }
        public Nullable<System.DateTime> DT_INICIO { get; set; }
        public string DS_NUMERO_CSI { get; set; }
        public Nullable<int> CD_LOCAL { get; set; }
        public Nullable<int> QT_VIAS_ORIGINAIS { get; set; }
        public Nullable<int> CD_TRADUTOR { get; set; }
        public Nullable<int> CD_CARTORIO { get; set; }
        public string DS_CARTORIO { get; set; }
        public Nullable<int> CD_EMBAIXADA { get; set; }
        public string DS_EMBAIXADA { get; set; }
        public Nullable<int> CD_CONSULADO { get; set; }
        public Nullable<System.DateTime> DT_CONSULADO { get; set; }
        public Nullable<int> CD_CAMARA_COMERCIO { get; set; }
        public string DS_CAMARA { get; set; }
        public Nullable<System.DateTime> DT_CAMARA { get; set; }
        public bool IC_CANCELADO { get; set; }
        public string DS_CANCELAMENTO { get; set; }
        public Nullable<bool> IC_ATIVO { get; set; }
        public Nullable<bool> IC_VETADO { get; set; }
        public string DS_VETADO { get; set; }
        public Nullable<decimal> VL_SEGURO_EMBUTIDO_TRAFEGO { get; set; }
        public Nullable<int> CD_USUARIO { get; set; }
        public Nullable<System.DateTime> DT_ABERTURA_PROCESSO { get; set; }
        public Nullable<bool> IC_ENCERRADO { get; set; }
        public Nullable<bool> IC_SEGURO_EMBUTIDO { get; set; }
        public string NM_LETRA_CONTAINER_TRAFEGO { get; set; }
        public Nullable<System.DateTime> DT_CONFIRMACAO_EMBARQUE { get; set; }
        public string DS_ENDERECO_IMPORTADOR { get; set; }
        public Nullable<int> CD_PAIS_IMPORTADOR { get; set; }
        public Nullable<System.DateTime> DT_ENCERRADO { get; set; }
        public Nullable<int> CD_USUARIO_ENCERROU { get; set; }
        public Nullable<int> CD_PAIS_RESERVA { get; set; }
        public Nullable<bool> IC_CNTR_GRANEL { get; set; }
        public Nullable<int> CD_TIPO_PROCESSO { get; set; }
        public Nullable<int> CD_TERMINAL_ESTUFAGEM { get; set; }
        public Nullable<int> CD_TIPO_ESTADO { get; set; }
        public Nullable<decimal> VL_PRE_PAGAMENTO_CAMBIO { get; set; }
        public Nullable<decimal> VL_ADIANTAMENTO_CAMBIO { get; set; }
        public Nullable<decimal> VL_DESCONTO_CAMBIO { get; set; }
        public string DS_VIA_TRANSITO { get; set; }
        public Nullable<int> CD_CANAL_PARAMETRIZACAO { get; set; }
        public string CD_NUMERO_CAIXA_ARQUIVO_MORTO { get; set; }
        public Nullable<System.DateTime> DT_NUMERO_CAIXA_ARQUIVO_MORTO { get; set; }
        public Nullable<System.DateTime> DT_FATURA { get; set; }
        public Nullable<int> DT_DIA_SEMANA_FATURA { get; set; }
        public Nullable<bool> IC_EMBARQUE_PROPRIO { get; set; }
        public string NM_PROCESSO_INTERNO { get; set; }
        public Nullable<int> CD_LOCAL_ORIGEM_TRAFEGO { get; set; }
        public Nullable<int> CD_SERVICO_PROCESSO { get; set; }
        public Nullable<int> CD_OPCAO_SUZANO { get; set; }
        public string CD_NUMERO_BL { get; set; }
        public Nullable<System.DateTime> DT_BL { get; set; }
        public string DS_IMPORTADOR_CAMBIO { get; set; }
        public Nullable<int> CD_ANALISTA_EXPORTADOR { get; set; }
        public string CD_NUMERO_CAIXA_ARQUIVO_MORTO2 { get; set; }
        public Nullable<System.DateTime> DT_NUMERO_CAIXA_ARQUIVO_MORTO2 { get; set; }
        public Nullable<decimal> VL_TOTAL_NOTA_FISCAL { get; set; }
        public string CD_NUMERO_BL_CAMBIO { get; set; }
        public string CD_NUMERO_CSI_CAMBIO { get; set; }
        public Nullable<decimal> VL_FOB_CAMBIO { get; set; }
        public Nullable<decimal> VL_FRETE_CAMBIO { get; set; }
        public Nullable<decimal> VL_SEGURO_CAMBIO { get; set; }
        public string DS_PORTO_ORIGEM_CAMBIO { get; set; }
        public string DS_PORTO_DESTINO_CAMBIO { get; set; }
        public string DS_DESTINO_FINAL_CAMBIO { get; set; }
        public string NR_CERTIFICADO_ORIGEM_CAMBIO { get; set; }
        public Nullable<System.DateTime> DT_CERTIFICADO_ORIGEM_CAMBIO { get; set; }
        public string NR_CNCA_CAMBIO { get; set; }
        public Nullable<System.DateTime> DT_CNCA_CAMBIO { get; set; }
        public string NR_FORM_A_CAMBIO { get; set; }
        public Nullable<System.DateTime> DT_SOLICITACAO_FORM_A_CAMBIO { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO_FORM_A_CAMBIO { get; set; }
        public string NR_FITOSSANITARIO_CAMBIO { get; set; }
        public Nullable<System.DateTime> DT_SOLICITACAO_FITOSSANITARIO_CAMBIO { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO_FITOSSANITARIO_CAMBIO { get; set; }
        public string NR_CERTIFICADO_ECTN_CAMBIO { get; set; }
        public Nullable<System.DateTime> DT_CERTIFICADO_ECTN_CAMBIO { get; set; }
        public Nullable<int> CD_FORMAPAGTO_EXPORTADOR { get; set; }
        public Nullable<int> CD_STATUS_OPERACIONAL { get; set; }
        public string DS_BANCO_EXTERIOR_CAMBIO { get; set; }
        public string DS_CONTA_GRAFICA_CAMBIO { get; set; }
        public Nullable<int> idStatusEmbarque { get; set; }
        public Nullable<int> ICEMBARQUECANCELADO { get; set; }
        public Nullable<int> CD_USUARIO_CANCELAMENTO { get; set; }
        public Nullable<System.DateTime> DT_CANCELAMENTO { get; set; }
        public Nullable<int> IC_NAO_MOSTRA_PROCESSO_FATURAMENTO { get; set; }
        public Nullable<int> IC_NAO_MOSTRA_PROCESSO_FATURAMENTO_OPER { get; set; }
        public Nullable<System.DateTime> DT_PROFORMA { get; set; }
        public string DS_VIGIAGRO_OBSERVACAO { get; set; }
        public string DS_CAMBIO_LIVRE1 { get; set; }
        public string DS_CAMBIO_LIVRE2 { get; set; }
        public string DS_CAMBIO_LIVRE3 { get; set; }
        public string DS_CAMBIO_LIVRE4 { get; set; }
        public string DS_CAMBIO_LIVRE5 { get; set; }
        public string CD_INCOTERM_CAMBIO { get; set; }
        public string DHL_CC { get; set; }
        public string DHL_NR { get; set; }
        public string DS_DADOS_CONTA_IMPORTADOR { get; set; }
        public string DS_RESP_CLIENTE { get; set; }
        public Nullable<System.DateTime> DT_COPIA_BL { get; set; }
        public Nullable<System.DateTime> DT_ORIGINAL_BL { get; set; }
        public Nullable<System.DateTime> DT_RECEBIMENTO_CSI { get; set; }
        public Nullable<System.DateTime> DT_PASTA_DRAFT { get; set; }
        public Nullable<System.DateTime> DT_PASTA_CAMBIO { get; set; }
        public Nullable<System.DateTime> DT_PASTA_FATURAMENTO { get; set; }
        public string SG_TIPO_CONFERENCIA_VIGIAGRO { get; set; }
        public string SG_STATUS_MAPA { get; set; }
        public string DS_OBSERVACAO { get; set; }
        public Nullable<System.DateTime> DT_TF_VIGIAGRO { get; set; }
        public Nullable<System.DateTime> DT_ENTRADA_TF { get; set; }
        public Nullable<int> CD_PRODUTO { get; set; }
        public Nullable<int> CD_RESPONSAVEL_BL { get; set; }
        public string DS_OBSERVACAO_VIGIAGRO { get; set; }
        public Nullable<int> CD_USUARIO_VIGIAGRO { get; set; }
        public Nullable<bool> IC_CTPNE { get; set; }
        public Nullable<bool> IC_CDPNE { get; set; }
        public Nullable<bool> SG_OCORRENCIA { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_EXP_VIGIAGRO { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_MAPA { get; set; }
        public Nullable<System.DateTime> DT_ENTRADA_CSI { get; set; }
        public Nullable<System.DateTime> DT_LIBERACAO_CSI { get; set; }
        public Nullable<int> CD_USUARIO_CAMBIO_ULTIMO { get; set; }
        public Nullable<System.DateTime> DT_DESEMBARACO { get; set; }
        public Nullable<System.DateTime> DT_ENTREGA_DESPACHO { get; set; }
        public string NR_DUE { get; set; }
        public string NR_RUC { get; set; }
        public Nullable<System.DateTime> DT_DESEMBARACO_DUE { get; set; }
        public Nullable<System.DateTime> DT_REGISTRO_DUE { get; set; }
        public Nullable<int> IC_STATUS_DUE { get; set; }
        public Nullable<System.DateTime> DT_CANAL_VERMELHO { get; set; }
        public Nullable<System.DateTime> DT_ANALISE_FISCAL { get; set; }
        public Nullable<System.DateTime> DT_EXPIRACAO_PRAZO { get; set; }
        public Nullable<int> IC_BLOQUEIO_DUE { get; set; }
        public Nullable<int> IC_CONTROLE_ADM_DUE { get; set; }
        public Nullable<System.DateTime> DT_BLOQUEIO_ADM { get; set; }
        public Nullable<System.DateTime> DT_AVERBADO { get; set; }
        public string DS_CONSIGNEE_NOTIFY { get; set; }
        public Nullable<int> CD_COUREIR { get; set; }
        public string NR_RASTREIO { get; set; }
        public string DS_COUREIR { get; set; }
        public string DS_ENVIO_DOCUMENTO { get; set; }
        public Nullable<int> CD_STATUS_DOCUMENTAL { get; set; }
        public string CD_NUMERO_BL_REAL { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_NUMERO_BL { get; set; }
        public Nullable<System.DateTime> DT_BL_REAL { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_BL { get; set; }
        public Nullable<System.DateTime> DT_ORDER_CONFIRMATION_DATE { get; set; }
        public Nullable<System.DateTime> DT_EMBARQUE { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_DATA_DESATRACACAO { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_COURIER { get; set; }
        public string NM_DESTINO_LEGALIZACAO { get; set; }
        public Nullable<int> QTD_VIAS_LEGALIZADO { get; set; }
        public string NR_CHAVE_NF { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_DOCS { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_EDI_DOCS { get; set; }
        public Nullable<int> CD_IMPORTADOR_CAMBIO { get; set; }
        public Nullable<int> CD_STATUS_HISTORICO_DUE { get; set; }
        public string NM_MODALIDADE_FATURA_CAMBIO { get; set; }
        public string DS_HALAL_CAMBIO { get; set; }
        public string DS_MERCADORIA_PT_CAMBIO { get; set; }
        public string DS_REFERENCIA_IMPORTADOR { get; set; }
        public Nullable<bool> IC_DOC_DESEMBARACO_OK { get; set; }
        public Nullable<int> IC_GERADO_EXTRATO_DUE_REGISTRADA { get; set; }
        public Nullable<int> IC_GERADO_EXTRATO_DUE_AVERBADA { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_EXTRATO_REGISTRADA { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_COPY_BL { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_EDI_EXCEL_AVERBADO { get; set; }
        public Nullable<bool> IC_ABERTURA_XML { get; set; }
        public Nullable<bool> IC_COTA_HILTON { get; set; }
        public Nullable<System.DateTime> DT_LIBEROU_DRAFT { get; set; }
        public string IC_ABERTURA { get; set; }
        public string DS_OBSERVACAO_FATURAMENTO { get; set; }
        public string NM_IMPORTADOR_CLIENTE { get; set; }
        public Nullable<int> CD_PROCESSO_IMPORTACAO { get; set; }
        public string CNEE { get; set; }
        public Nullable<System.DateTime> DT_ALERTA_REPRESENTACAO { get; set; }
        public string ALTERACAO_CLIENTE { get; set; }
        public Nullable<bool> IC_MERCADO_INTERNO { get; set; }
        public string CD_RUC { get; set; }
        public Nullable<int> CD_RESPONSAVEL_CLIENTE { get; set; }
        public Nullable<System.DateTime> DT_ENVIO_EMAIL_DESATRACACAO_CLIENTE { get; set; }
        public string DS_POLITICA_SEGURO_CAMBIO { get; set; }
        public Nullable<bool> IC_REVENDA { get; set; }
        public string DS_BUYER { get; set; }
        public Nullable<System.DateTime> DT_SUSPENSO { get; set; }
    
        public virtual ICollection<PROCESSORESERVA> PROCESSORESERVA { get; set; }
        public virtual LOCAIS LOCAIS { get; set; }
        public virtual ICollection<PROCESSOEVENTO> PROCESSOEVENTO { get; set; }
        public virtual ICollection<PROCESSO_LOTE> PROCESSO_LOTE { get; set; }
        public virtual ICollection<PROCESSO_LOTE> PROCESSO_LOTE1 { get; set; }
        public virtual ICollection<DDE> DDE { get; set; }
        public virtual ENTIDADE ENTIDADE { get; set; }
        public virtual ENTIDADE ENTIDADE1 { get; set; }
        public virtual ENTIDADE ENTIDADE2 { get; set; }
        public virtual ENTIDADE ENTIDADE3 { get; set; }
        public virtual ENTIDADE ENTIDADE4 { get; set; }
        public virtual ENTIDADE ENTIDADE5 { get; set; }
        public virtual ENTIDADE ENTIDADE6 { get; set; }
        public virtual ENTIDADE ENTIDADE7 { get; set; }
        public virtual ENTIDADE ENTIDADE8 { get; set; }
        public virtual ENTIDADE ENTIDADE9 { get; set; }
        public virtual ENTIDADE ENTIDADE10 { get; set; }
        public virtual ENTIDADE ENTIDADE11 { get; set; }
        public virtual ICollection<DUE> DUE { get; set; }
    }
}
