//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIALFA
    {
        public RECIALFA()
        {
            this.DDE = new HashSet<DDE>();
            this.DUE = new HashSet<DUE>();
            this.DUE1 = new HashSet<DUE>();
        }
    
        public string STR_CODIGORECIALFA { get; set; }
        public string STR_DESCRICAO { get; set; }
        public string STR_CODIGOURFEMBARQUE { get; set; }
        public string STR_FANTASIA { get; set; }
        public Nullable<int> CD_ENTIDADE { get; set; }
        public Nullable<int> CD_FILIAL { get; set; }
        public string DS_EMAIL_RECINTO { get; set; }
    
        public virtual ICollection<DDE> DDE { get; set; }
        public virtual ICollection<DUE> DUE { get; set; }
        public virtual ICollection<DUE> DUE1 { get; set; }
    }
}
