//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELAC_EXPORTADOR
    {
        public int CD_RELAC_EXPORTADOR { get; set; }
        public int CD_ENTIDADE { get; set; }
        public string DS_RELAC_EXPORTADOR { get; set; }
        public string CD_SIF { get; set; }
        public string DS_URL_LOGO { get; set; }
        public string NM_LOGO { get; set; }
        public string DS_RELAC_EXPORTADOR_BL { get; set; }
        public string DS_BANCO_EXTERIOR { get; set; }
        public string DHL_CC { get; set; }
        public string DHL_NR { get; set; }
        public Nullable<int> IC_PROTECAO_AEREO { get; set; }
        public Nullable<decimal> VL_PROTECAO_AEREO { get; set; }
        public Nullable<int> IC_PROTECAO_MARITIMA { get; set; }
        public Nullable<decimal> VL_PROTECAO_MARITIMA { get; set; }
        public Nullable<System.DateTime> DT_REPRESENTACAO { get; set; }
        public Nullable<int> CD_FORMA_PAGAMENTO { get; set; }
        public Nullable<int> CD_MODO_PAGAMENTO { get; set; }
        public Nullable<int> QTD_DIAS_VENCIMENTO { get; set; }
        public string DS_DIA_QUINZENAL { get; set; }
        public string DS_DIA_ESPECIFICO { get; set; }
        public Nullable<int> CD_SACADO { get; set; }
        public Nullable<int> QTD_DIA_LIMITE_FATURAMENTO { get; set; }
        public Nullable<int> CD_CONTABANCARIA_BOLETO { get; set; }
        public Nullable<int> QTD_MIN_FATURA_NA_NOTA_FISCAL { get; set; }
        public Nullable<int> QTD_MAX_FATURA_NA_NOTA_FISCAL { get; set; }
        public string IC_ENVIO_FATURA_BOLETO { get; set; }
        public string NM_EMAIL_ENVIO_FATURA_BOLETO { get; set; }
        public Nullable<int> QTD_MAX_FATURA_NO_BOLETO { get; set; }
        public Nullable<int> CD_DIA_SEMANA { get; set; }
        public string IC_ENVIO_NOME_ARQUIVO_BOL_TRANS { get; set; }
        public Nullable<System.DateTime> DT_ATUALIZACAO_LOGO { get; set; }
        public Nullable<bool> IC_DUE_POR_FORA { get; set; }
    
        public virtual ENTIDADE ENTIDADE { get; set; }
    }
}
