//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELACIONAMENTOENTIDADE
    {
        public int CD_ENTIDADE { get; set; }
        public int CD_TIPO_RELAC_ENTIDADE { get; set; }
        public Nullable<int> CD_EMPRESA { get; set; }
        public Nullable<int> CD_FILIAL { get; set; }
    
        public virtual ENTIDADE ENTIDADE { get; set; }
    }
}
