//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVAS
    {
        public RESERVAS()
        {
            this.PROCESSORESERVA = new HashSet<PROCESSORESERVA>();
        }
    
        public int CD_RESERVA { get; set; }
        public int CD_VIAGEM_ARMADOR { get; set; }
        public string CD_NUMERO_RESERVA { get; set; }
        public Nullable<int> CD_ENTIDADE { get; set; }
        public Nullable<int> CD_PORTO_ORIGEM { get; set; }
        public Nullable<int> CD_PORTO_DESTINO { get; set; }
        public Nullable<int> CD_DESTINO_FINAL { get; set; }
        public Nullable<int> CD_PAIS_RESERVA { get; set; }
        public Nullable<System.DateTime> DT_SOLICITA_RETIRADA { get; set; }
        public Nullable<int> CD_DEPOT { get; set; }
        public Nullable<System.DateTime> DT_ETA_DESTINO_RESERVA { get; set; }
    
        public virtual ICollection<PROCESSORESERVA> PROCESSORESERVA { get; set; }
    }
}
