//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUS_PROCESSO
    {
        public int CD_STATUS_PROCESSO { get; set; }
        public string NM_STATUS_PROCESSO { get; set; }
        public string SG_OPERACAO { get; set; }
        public string SG_TRANSPORTE { get; set; }
        public string SG_TIPO_STATUS { get; set; }
        public Nullable<System.DateTime> DT_INATIVO { get; set; }
        public Nullable<bool> IC_EMBARQUE_CANCELADO { get; set; }
    }
}
