//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_CONSULTA_EMBARQUE
    {
        public int CD_CHAVE { get; set; }
        public Nullable<int> CD_PROCESSO { get; set; }
        public string CD_NUMERO_PROCESSO { get; set; }
        public string NR_CONTAINER { get; set; }
        public Nullable<System.DateTime> DT_CONTAINER { get; set; }
        public Nullable<System.DateTime> DT_EMBARQUE { get; set; }
        public string NR_BOOKING { get; set; }
        public string NR_BOOKING_TERMINAL { get; set; }
        public string NM_NAVIO { get; set; }
        public string NM_NAVIO_TERMINAL { get; set; }
        public string DS_STATUS { get; set; }
        public string NR_DUE { get; set; }
        public string NR_DUE_TERMINAL { get; set; }
        public Nullable<System.DateTime> DT_CONSULTA { get; set; }
        public string NM_TERMINAL { get; set; }
        public Nullable<System.DateTime> DT_PROTOCOLADO { get; set; }
        public string NM_PROCESSO_STATUS2 { get; set; }
        public Nullable<System.DateTime> DT_DEPOSITO { get; set; }
        public string IC_TIPO { get; set; }
        public string NM_TERMINAL_SISTEMA { get; set; }
        public Nullable<System.DateTime> DT_ETA { get; set; }
        public string DS_REFERENCIA_CLIENTE { get; set; }
        public string DS_LACRE_AGENCIA { get; set; }
        public string DS_LACRE_AGENCIA_TERMINAL { get; set; }
        public string DS_LACRE_SIF { get; set; }
        public string DS_LACRE_SIF_TERMINAL { get; set; }
        public Nullable<int> IC_ROBO { get; set; }
    }
}
