//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_CONSULTA_NAVIO
    {
        public int CD_CHAVE { get; set; }
        public Nullable<int> CD_VIAGEM { get; set; }
        public Nullable<int> CD_TERMINAL { get; set; }
        public string NM_TERMINAL { get; set; }
        public string NM_NAVIO { get; set; }
        public Nullable<System.DateTime> DT_ETA { get; set; }
        public Nullable<System.DateTime> DT_ATRACACAO { get; set; }
        public Nullable<System.DateTime> DT_ETA_TERMINAL { get; set; }
        public Nullable<System.DateTime> DT_DESATRACACAO { get; set; }
        public string NR_VIAGEM { get; set; }
    }
}
