//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDRF
    {
        public UNIDRF()
        {
            this.DDE = new HashSet<DDE>();
            this.DDE1 = new HashSet<DDE>();
            this.DUE = new HashSet<DUE>();
            this.DUE1 = new HashSet<DUE>();
        }
    
        public string STR_CODIGOUNIDADERF { get; set; }
        public string STR_CODIGOVIATRANSPORTE { get; set; }
        public string STR_NOMEUNIDADERF { get; set; }
        public string STR_GRUPOREGISTRORF { get; set; }
        public string STR_DIGITO { get; set; }
        public string STR_NOMEREDUZIDO { get; set; }
        public string STR_DESCRICAOINGLES { get; set; }
        public string STR_CODIGOEXTERNO { get; set; }
        public Nullable<int> CD_ENTIDADE { get; set; }
        public Nullable<int> CD_FILIAL { get; set; }
    
        public virtual ICollection<DDE> DDE { get; set; }
        public virtual ICollection<DDE> DDE1 { get; set; }
        public virtual ICollection<DUE> DUE { get; set; }
        public virtual ICollection<DUE> DUE1 { get; set; }
    }
}
