//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_CA
    {
        public USUARIO_CA()
        {
            this.USUARIO_CA1 = new HashSet<USUARIO_CA>();
            this.USUARIO_CA11 = new HashSet<USUARIO_CA>();
            this.USUARIO_CA12 = new HashSet<USUARIO_CA>();
        }
    
        public int CD_USUARIO { get; set; }
        public string NM_USUARIO { get; set; }
        public string NM_LOGIN { get; set; }
        public string CD_SENHA { get; set; }
        public Nullable<int> CD_USUARIO_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO { get; set; }
        public Nullable<int> CD_USUARIO_CANCEL { get; set; }
        public Nullable<System.DateTime> DT_CANCEL { get; set; }
        public Nullable<int> CD_USUARIO_ALTERACAO { get; set; }
        public Nullable<System.DateTime> DT_ATERACAO { get; set; }
        public Nullable<int> CD_ENTIDADE { get; set; }
        public Nullable<int> CD_EMPRESA { get; set; }
        public Nullable<int> CD_FILIAL { get; set; }
        public Nullable<int> CD_PERIODO { get; set; }
        public Nullable<int> CD_GRUPOCLIENTE { get; set; }
        public Nullable<int> CD_CLIENTE { get; set; }
        public Nullable<System.DateTime> DT_DATA_INICIO_1 { get; set; }
        public Nullable<System.DateTime> DT_DATA_FIM_1 { get; set; }
        public Nullable<System.DateTime> DT_DATA_INICIO_2 { get; set; }
        public Nullable<System.DateTime> DT_DATA_FIM_2 { get; set; }
        public Nullable<System.DateTime> DT_DATA_INICIO_3 { get; set; }
        public Nullable<System.DateTime> DT_DATA_FIM_3 { get; set; }
        public string DS_BOOKING { get; set; }
        public string DS_PROCESSO { get; set; }
        public Nullable<int> IC_TIPO { get; set; }
        public string DS_IMAGEM { get; set; }
        public Nullable<System.DateTime> DT_DATA_INICIO_4 { get; set; }
        public Nullable<System.DateTime> DT_DATA_FIM_4 { get; set; }
        public Nullable<int> ID_NAVIO { get; set; }
        public Nullable<int> ID_SERVICO { get; set; }
        public Nullable<int> ID_USUARIO_IMPORTACAO { get; set; }
        public string DS_REFERENCIA { get; set; }
        public Nullable<int> ID_SPID { get; set; }
        public string CD_STATUS { get; set; }
        public string IC_NIVEL_CARGO { get; set; }
        public string NM_EMAIL { get; set; }
        public string NR_CONTAINER { get; set; }
        public string CD_GRUPOCLIENTE_ARRAY { get; set; }
        public Nullable<int> CD_GRUPO_FINANCEIRO { get; set; }
        public string CD_STATUS_DRAFT_ARRAY { get; set; }
        public string CD_IMPORTADOR { get; set; }
        public string DS_DESTINO { get; set; }
        public string CSI { get; set; }
        public Nullable<int> BARRA_LATERAL { get; set; }
        public string DS_SENHA_SHA256 { get; set; }
        public string GUID { get; set; }
        public Nullable<System.DateTime> DT_DATA_INICIO_5 { get; set; }
        public Nullable<System.DateTime> DT_DATA_FIM_5 { get; set; }
        public string NR_DUE { get; set; }
        public Nullable<int> QTD_NOTIFICACAO { get; set; }
    
        public virtual ICollection<USUARIO_CA> USUARIO_CA1 { get; set; }
        public virtual USUARIO_CA USUARIO_CA2 { get; set; }
        public virtual ICollection<USUARIO_CA> USUARIO_CA11 { get; set; }
        public virtual USUARIO_CA USUARIO_CA3 { get; set; }
        public virtual ICollection<USUARIO_CA> USUARIO_CA12 { get; set; }
        public virtual USUARIO_CA USUARIO_CA4 { get; set; }
        public virtual ENTIDADE ENTIDADE { get; set; }
    }
}
