//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAGEMARMADOR
    {
        public int CD_VIAGEM_ARMADOR { get; set; }
        public int CD_VIAGEM { get; set; }
        public int CD_ARMADOR { get; set; }
        public Nullable<int> CD_OPERADOR_PORTUARIO { get; set; }
        public Nullable<System.DateTime> DT_ETB { get; set; }
        public Nullable<System.DateTime> DT_ATRACACAO { get; set; }
        public Nullable<System.DateTime> DT_ETS { get; set; }
        public Nullable<System.DateTime> DT_DESATRACACAO { get; set; }
        public Nullable<System.DateTime> DT_DEAD_LINE_DRAFT { get; set; }
        public Nullable<System.DateTime> DT_DEAD_LINE_CONTAINER { get; set; }
        public Nullable<System.DateTime> DT_DEAD_LINE_SD { get; set; }
        public string DS_FONTE_ULTIMA_ATUALIZACAO { get; set; }
        public string DS_OBSERVACAO { get; set; }
        public Nullable<int> CD_EMPRESA { get; set; }
        public Nullable<int> CD_FILIAL { get; set; }
        public Nullable<int> CD_TERMINAL_ATRACACAO { get; set; }
        public Nullable<int> CD_USUARIO_DESATRACACAO { get; set; }
        public Nullable<int> CD_AGENTE_CARGA { get; set; }
        public Nullable<bool> IC_EMBARQUE_CONFIRMADO { get; set; }
        public Nullable<bool> IC_EDI_DISPARADO { get; set; }
        public Nullable<int> CD_TERMINAL_CABOTAGEM { get; set; }
    }
}
