//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIAGEM
    {
        public int CD_VIAGEM { get; set; }
        public string CD_NUMERO_VIAGEM { get; set; }
        public Nullable<int> CD_NAVIO { get; set; }
        public Nullable<int> CD_ARMADOR { get; set; }
        public Nullable<bool> IC_VIAGEM_ENCERRADA { get; set; }
        public Nullable<System.DateTime> DT_ETA { get; set; }
        public Nullable<int> CD_EMPRESA { get; set; }
        public Nullable<int> CD_FILIAL { get; set; }
        public Nullable<int> CD_PORTO_ORIGEM { get; set; }
        public Nullable<System.DateTime> DT_ETA_DEST { get; set; }
        public Nullable<System.DateTime> DT_ETD { get; set; }
    }
}
