//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TerminalRobo.ServiceRefMinerva {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Autenticacao", Namespace="http://www.minervafoods.com")]
    [System.SerializableAttribute()]
    public partial class Autenticacao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string senhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                if ((object.ReferenceEquals(this.senhaField, value) != true)) {
                    this.senhaField = value;
                    this.RaisePropertyChanged("senha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ordem", Namespace="http://www.minervafoods.com")]
    [System.SerializableAttribute()]
    public partial class Ordem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Num_LPCOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChaveAcessoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DUEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUCField;
        
        private System.Nullable<System.DateTime> DtaRegistroField;
        
        private System.Nullable<System.DateTime> DtaDesembaracoField;
        
        private System.Nullable<System.DateTime> DtaEmbarqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Num_BLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumControleSatelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalEmbarqueField;
        
        private System.Nullable<System.DateTime> DtaEntradaTerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalArmazenagemField;
        
        private System.Nullable<System.DateTime> DtaEntradaArmazenagemField;
        
        private System.Nullable<System.DateTime> DtaSaidaNavioField;
        
        private System.Nullable<System.DateTime> DtaDespachoField;
        
        private System.Nullable<System.DateTime> DtaCSIField;
        
        private System.Nullable<System.DateTime> DtaDraftField;
        
        private System.Nullable<System.DateTime> DtaDocsProntosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NrCourierField;
        
        private System.Nullable<System.DateTime> DtaEnvioCourierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacoesField;
        
        private System.Nullable<System.DateTime> DtaCargaExpTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificadoSanitarioField;
        
        private System.Nullable<System.DateTime> DtaLiberacaoBLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodEmpresa {
            get {
                return this.CodEmpresaField;
            }
            set {
                if ((this.CodEmpresaField.Equals(value) != true)) {
                    this.CodEmpresaField = value;
                    this.RaisePropertyChanged("CodEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Ordens {
            get {
                return this.OrdensField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdensField, value) != true)) {
                    this.OrdensField = value;
                    this.RaisePropertyChanged("Ordens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Num_LPCO {
            get {
                return this.Num_LPCOField;
            }
            set {
                if ((object.ReferenceEquals(this.Num_LPCOField, value) != true)) {
                    this.Num_LPCOField = value;
                    this.RaisePropertyChanged("Num_LPCO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ChaveAcesso {
            get {
                return this.ChaveAcessoField;
            }
            set {
                if ((object.ReferenceEquals(this.ChaveAcessoField, value) != true)) {
                    this.ChaveAcessoField = value;
                    this.RaisePropertyChanged("ChaveAcesso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DUE {
            get {
                return this.DUEField;
            }
            set {
                if ((object.ReferenceEquals(this.DUEField, value) != true)) {
                    this.DUEField = value;
                    this.RaisePropertyChanged("DUE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RUC {
            get {
                return this.RUCField;
            }
            set {
                if ((object.ReferenceEquals(this.RUCField, value) != true)) {
                    this.RUCField = value;
                    this.RaisePropertyChanged("RUC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<System.DateTime> DtaRegistro {
            get {
                return this.DtaRegistroField;
            }
            set {
                if ((this.DtaRegistroField.Equals(value) != true)) {
                    this.DtaRegistroField = value;
                    this.RaisePropertyChanged("DtaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<System.DateTime> DtaDesembaraco {
            get {
                return this.DtaDesembaracoField;
            }
            set {
                if ((this.DtaDesembaracoField.Equals(value) != true)) {
                    this.DtaDesembaracoField = value;
                    this.RaisePropertyChanged("DtaDesembaraco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<System.DateTime> DtaEmbarque {
            get {
                return this.DtaEmbarqueField;
            }
            set {
                if ((this.DtaEmbarqueField.Equals(value) != true)) {
                    this.DtaEmbarqueField = value;
                    this.RaisePropertyChanged("DtaEmbarque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Num_BL {
            get {
                return this.Num_BLField;
            }
            set {
                if ((object.ReferenceEquals(this.Num_BLField, value) != true)) {
                    this.Num_BLField = value;
                    this.RaisePropertyChanged("Num_BL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string NumControleSatel {
            get {
                return this.NumControleSatelField;
            }
            set {
                if ((object.ReferenceEquals(this.NumControleSatelField, value) != true)) {
                    this.NumControleSatelField = value;
                    this.RaisePropertyChanged("NumControleSatel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TerminalEmbarque {
            get {
                return this.TerminalEmbarqueField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalEmbarqueField, value) != true)) {
                    this.TerminalEmbarqueField = value;
                    this.RaisePropertyChanged("TerminalEmbarque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<System.DateTime> DtaEntradaTerminal {
            get {
                return this.DtaEntradaTerminalField;
            }
            set {
                if ((this.DtaEntradaTerminalField.Equals(value) != true)) {
                    this.DtaEntradaTerminalField = value;
                    this.RaisePropertyChanged("DtaEntradaTerminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string TerminalArmazenagem {
            get {
                return this.TerminalArmazenagemField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalArmazenagemField, value) != true)) {
                    this.TerminalArmazenagemField = value;
                    this.RaisePropertyChanged("TerminalArmazenagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<System.DateTime> DtaEntradaArmazenagem {
            get {
                return this.DtaEntradaArmazenagemField;
            }
            set {
                if ((this.DtaEntradaArmazenagemField.Equals(value) != true)) {
                    this.DtaEntradaArmazenagemField = value;
                    this.RaisePropertyChanged("DtaEntradaArmazenagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<System.DateTime> DtaSaidaNavio {
            get {
                return this.DtaSaidaNavioField;
            }
            set {
                if ((this.DtaSaidaNavioField.Equals(value) != true)) {
                    this.DtaSaidaNavioField = value;
                    this.RaisePropertyChanged("DtaSaidaNavio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.Nullable<System.DateTime> DtaDespacho {
            get {
                return this.DtaDespachoField;
            }
            set {
                if ((this.DtaDespachoField.Equals(value) != true)) {
                    this.DtaDespachoField = value;
                    this.RaisePropertyChanged("DtaDespacho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<System.DateTime> DtaCSI {
            get {
                return this.DtaCSIField;
            }
            set {
                if ((this.DtaCSIField.Equals(value) != true)) {
                    this.DtaCSIField = value;
                    this.RaisePropertyChanged("DtaCSI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Nullable<System.DateTime> DtaDraft {
            get {
                return this.DtaDraftField;
            }
            set {
                if ((this.DtaDraftField.Equals(value) != true)) {
                    this.DtaDraftField = value;
                    this.RaisePropertyChanged("DtaDraft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.Nullable<System.DateTime> DtaDocsProntos {
            get {
                return this.DtaDocsProntosField;
            }
            set {
                if ((this.DtaDocsProntosField.Equals(value) != true)) {
                    this.DtaDocsProntosField = value;
                    this.RaisePropertyChanged("DtaDocsProntos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Courier {
            get {
                return this.CourierField;
            }
            set {
                if ((object.ReferenceEquals(this.CourierField, value) != true)) {
                    this.CourierField = value;
                    this.RaisePropertyChanged("Courier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string NrCourier {
            get {
                return this.NrCourierField;
            }
            set {
                if ((object.ReferenceEquals(this.NrCourierField, value) != true)) {
                    this.NrCourierField = value;
                    this.RaisePropertyChanged("NrCourier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public System.Nullable<System.DateTime> DtaEnvioCourier {
            get {
                return this.DtaEnvioCourierField;
            }
            set {
                if ((this.DtaEnvioCourierField.Equals(value) != true)) {
                    this.DtaEnvioCourierField = value;
                    this.RaisePropertyChanged("DtaEnvioCourier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string Observacoes {
            get {
                return this.ObservacoesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacoesField, value) != true)) {
                    this.ObservacoesField = value;
                    this.RaisePropertyChanged("Observacoes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public System.Nullable<System.DateTime> DtaCargaExpTotal {
            get {
                return this.DtaCargaExpTotalField;
            }
            set {
                if ((this.DtaCargaExpTotalField.Equals(value) != true)) {
                    this.DtaCargaExpTotalField = value;
                    this.RaisePropertyChanged("DtaCargaExpTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string CertificadoSanitario {
            get {
                return this.CertificadoSanitarioField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificadoSanitarioField, value) != true)) {
                    this.CertificadoSanitarioField = value;
                    this.RaisePropertyChanged("CertificadoSanitario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public System.Nullable<System.DateTime> DtaLiberacaoBL {
            get {
                return this.DtaLiberacaoBLField;
            }
            set {
                if ((this.DtaLiberacaoBLField.Equals(value) != true)) {
                    this.DtaLiberacaoBLField = value;
                    this.RaisePropertyChanged("DtaLiberacaoBL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoPadrao", Namespace="http://www.minervafoods.com")]
    [System.SerializableAttribute()]
    public partial class RetornoPadrao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool RetornoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgRetornoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Retorno {
            get {
                return this.RetornoField;
            }
            set {
                if ((this.RetornoField.Equals(value) != true)) {
                    this.RetornoField = value;
                    this.RaisePropertyChanged("Retorno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MsgRetorno {
            get {
                return this.MsgRetornoField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgRetornoField, value) != true)) {
                    this.MsgRetornoField = value;
                    this.RaisePropertyChanged("MsgRetorno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.minervafoods.com", ConfigurationName="ServiceRefMinerva.WSIntegraSatelSoap")]
    public interface WSIntegraSatelSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento autenticacao no namespace http://www.minervafoods.com não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://www.minervafoods.com/StatusOrdem", ReplyAction="*")]
        TerminalRobo.ServiceRefMinerva.StatusOrdemResponse StatusOrdem(TerminalRobo.ServiceRefMinerva.StatusOrdemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.minervafoods.com/StatusOrdem", ReplyAction="*")]
        System.Threading.Tasks.Task<TerminalRobo.ServiceRefMinerva.StatusOrdemResponse> StatusOrdemAsync(TerminalRobo.ServiceRefMinerva.StatusOrdemRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusOrdemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatusOrdem", Namespace="http://www.minervafoods.com", Order=0)]
        public TerminalRobo.ServiceRefMinerva.StatusOrdemRequestBody Body;
        
        public StatusOrdemRequest() {
        }
        
        public StatusOrdemRequest(TerminalRobo.ServiceRefMinerva.StatusOrdemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.minervafoods.com")]
    public partial class StatusOrdemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TerminalRobo.ServiceRefMinerva.Autenticacao autenticacao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TerminalRobo.ServiceRefMinerva.Ordem ordens;
        
        public StatusOrdemRequestBody() {
        }
        
        public StatusOrdemRequestBody(TerminalRobo.ServiceRefMinerva.Autenticacao autenticacao, TerminalRobo.ServiceRefMinerva.Ordem ordens) {
            this.autenticacao = autenticacao;
            this.ordens = ordens;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusOrdemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatusOrdemResponse", Namespace="http://www.minervafoods.com", Order=0)]
        public TerminalRobo.ServiceRefMinerva.StatusOrdemResponseBody Body;
        
        public StatusOrdemResponse() {
        }
        
        public StatusOrdemResponse(TerminalRobo.ServiceRefMinerva.StatusOrdemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.minervafoods.com")]
    public partial class StatusOrdemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TerminalRobo.ServiceRefMinerva.RetornoPadrao StatusOrdemResult;
        
        public StatusOrdemResponseBody() {
        }
        
        public StatusOrdemResponseBody(TerminalRobo.ServiceRefMinerva.RetornoPadrao StatusOrdemResult) {
            this.StatusOrdemResult = StatusOrdemResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSIntegraSatelSoapChannel : TerminalRobo.ServiceRefMinerva.WSIntegraSatelSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSIntegraSatelSoapClient : System.ServiceModel.ClientBase<TerminalRobo.ServiceRefMinerva.WSIntegraSatelSoap>, TerminalRobo.ServiceRefMinerva.WSIntegraSatelSoap {
        
        public WSIntegraSatelSoapClient() {
        }
        
        public WSIntegraSatelSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSIntegraSatelSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSIntegraSatelSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSIntegraSatelSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TerminalRobo.ServiceRefMinerva.StatusOrdemResponse TerminalRobo.ServiceRefMinerva.WSIntegraSatelSoap.StatusOrdem(TerminalRobo.ServiceRefMinerva.StatusOrdemRequest request) {
            return base.Channel.StatusOrdem(request);
        }
        
        public TerminalRobo.ServiceRefMinerva.RetornoPadrao StatusOrdem(TerminalRobo.ServiceRefMinerva.Autenticacao autenticacao, TerminalRobo.ServiceRefMinerva.Ordem ordens) {
            TerminalRobo.ServiceRefMinerva.StatusOrdemRequest inValue = new TerminalRobo.ServiceRefMinerva.StatusOrdemRequest();
            inValue.Body = new TerminalRobo.ServiceRefMinerva.StatusOrdemRequestBody();
            inValue.Body.autenticacao = autenticacao;
            inValue.Body.ordens = ordens;
            TerminalRobo.ServiceRefMinerva.StatusOrdemResponse retVal = ((TerminalRobo.ServiceRefMinerva.WSIntegraSatelSoap)(this)).StatusOrdem(inValue);
            return retVal.Body.StatusOrdemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TerminalRobo.ServiceRefMinerva.StatusOrdemResponse> TerminalRobo.ServiceRefMinerva.WSIntegraSatelSoap.StatusOrdemAsync(TerminalRobo.ServiceRefMinerva.StatusOrdemRequest request) {
            return base.Channel.StatusOrdemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TerminalRobo.ServiceRefMinerva.StatusOrdemResponse> StatusOrdemAsync(TerminalRobo.ServiceRefMinerva.Autenticacao autenticacao, TerminalRobo.ServiceRefMinerva.Ordem ordens) {
            TerminalRobo.ServiceRefMinerva.StatusOrdemRequest inValue = new TerminalRobo.ServiceRefMinerva.StatusOrdemRequest();
            inValue.Body = new TerminalRobo.ServiceRefMinerva.StatusOrdemRequestBody();
            inValue.Body.autenticacao = autenticacao;
            inValue.Body.ordens = ordens;
            return ((TerminalRobo.ServiceRefMinerva.WSIntegraSatelSoap)(this)).StatusOrdemAsync(inValue);
        }
    }
}
